"""第二轮扩展:追加药物到500+。"""
import sys, importlib
sys.path.insert(0, ".")
import app.graph.drug_data as dd
importlib.reload(dd)

existing_ids = {d["id"] for d in dd.DRUGS}
existing_interactions = set()
for a, b, s, m in dd.INTERACTIONS:
    existing_interactions.add((a, b))
    existing_interactions.add((b, a))

# ========== 第二批药物 ==========
MORE_DRUGS = [
    # 心血管补充
    {"id": "azilsartan", "name": "阿齐沙坦", "category": "ARB", "generic_name": "阿齐沙坦酯",
     "contraindications": ["孕妇", "双侧肾动脉狭窄"], "side_effects": ["低血压", "高钾血症"], "metabolism": "CYP2C9"},
    {"id": "olmesartan", "name": "奥美沙坦", "category": "ARB", "generic_name": "奥美沙坦酯",
     "contraindications": ["孕妇", "双侧肾动脉狭窄"], "side_effects": ["低血压", "高钾血症"], "metabolism": "CYP2C9"},
    {"id": "irbesartan", "name": "厄贝沙坦", "category": "ARB", "generic_name": "厄贝沙坦",
     "contraindications": ["孕妇", "双侧肾动脉狭窄"], "side_effects": ["低血压", "高钾血症"], "metabolism": "CYP2C9"},
    {"id": "candesartan", "name": "坎地沙坦", "category": "ARB", "generic_name": "坎地沙坦酯",
     "contraindications": ["孕妇", "双侧肾动脉狭窄"], "side_effects": ["低血压", "高钾血症"], "metabolism": "CYP2C9"},
    {"id": "telmisartan", "name": "替米沙坦", "category": "ARB", "generic_name": "替米沙坦",
     "contraindications": ["孕妇", "双侧肾动脉狭窄"], "side_effects": ["低血压", "高钾血症"], "metabolism": "UGT1A3"},
    {"id": "perindopril", "name": "培哚普利", "category": "ACEI", "generic_name": "培哚普利叔丁胺",
     "contraindications": ["血管性水肿史", "孕妇", "双侧肾动脉狭窄"], "side_effects": ["干咳", "高钾血症"], "metabolism": "CYP3A4"},
    {"id": "trandolapril", "name": "群多普利", "category": "ACEI", "generic_name": "群多普利",
     "contraindications": ["血管性水肿史", "孕妇"], "side_effects": ["干咳", "高钾血症"], "metabolism": "CYP3A4"},
    {"id": "fosinopril", "name": "福辛普利", "category": "ACEI", "generic_name": "福辛普利钠",
     "contraindications": ["血管性水肿史", "孕妇"], "side_effects": ["干咳", "高钾血症"], "metabolism": "肝肾双通道"},
    {"id": "benazepril", "name": "贝那普利", "category": "ACEI", "generic_name": "盐酸贝那普利",
     "contraindications": ["血管性水肿史", "孕妇"], "side_effects": ["干咳", "高钾血症"], "metabolism": "CYP3A4"},
    {"id": "doxazosin", "name": "多沙唑嗪", "category": "α受体阻滞剂", "generic_name": "甲磺酸多沙唑嗪",
     "contraindications": ["体位性低血压"], "side_effects": ["低血压", "头晕", "鼻塞"], "metabolism": "CYP3A4"},
    {"id": "prazosin", "name": "哌唑嗪", "category": "α受体阻滞剂", "generic_name": "盐酸哌唑嗪",
     "contraindications": ["对本品过敏"], "side_effects": ["首剂低血压", "头晕"], "metabolism": "CYP3A4"},
    {"id": "terazosin", "name": "特拉唑嗪", "category": "α受体阻滞剂", "generic_name": "盐酸特拉唑嗪",
     "contraindications": ["体位性低血压"], "side_effects": ["低血压", "头晕"], "metabolism": "CYP3A4"},
    {"id": "indapamide", "name": "吲达帕胺", "category": "利尿药", "generic_name": "吲达帕胺",
     "contraindications": ["严重肝功能不全", "低钾血症"], "side_effects": ["低钾血症", "高尿酸血症"], "metabolism": "CYP3A4"},
    {"id": "hydrochlorothiazide", "name": "氢氯噻嗪", "category": "利尿药", "generic_name": "氢氯噻嗪",
     "contraindications": ["无尿", "严重电解质紊乱"], "side_effects": ["低钾血症", "高尿酸血症", "高血糖"], "metabolism": "不代谢"},
    {"id": "chlorthalidone", "name": "氯噻酮", "category": "利尿药", "generic_name": "氯噻酮",
     "contraindications": ["无尿", "严重肝肾功能不全"], "side_effects": ["低钾血症", "高尿酸血症"], "metabolism": "肾脏排泄"},
    {"id": "amiloride", "name": "阿米洛利", "category": "利尿药", "generic_name": "盐酸阿米洛利",
     "contraindications": ["高钾血症", "严重肾功能不全"], "side_effects": ["高钾血症"], "metabolism": "不代谢"},
    {"id": "triamterene", "name": "氨苯蝶啶", "category": "利尿药", "generic_name": "氨苯蝶啶",
     "contraindications": ["高钾血症", "严重肾功能不全"], "side_effects": ["高钾血症", "肾结石"], "metabolism": "CYP1A2"},
    {"id": "acetazolamide", "name": "乙酰唑胺", "category": "利尿药", "generic_name": "乙酰唑胺",
     "contraindications": ["低钠血症", "低钾血症", "严重肝功能不全"], "side_effects": ["代谢性酸中毒", "感觉异常"], "metabolism": "不代谢"},
    {"id": "nesiritide", "name": "奈西立肽", "category": "心衰药", "generic_name": "奈西立肽",
     "contraindications": ["心源性休克", "收缩压<90mmHg"], "side_effects": ["低血压"], "metabolism": "蛋白水解"},
    {"id": "ivabradine_hf", "name": "伊伐布雷定(心衰)", "category": "抗心绞痛药",
     "generic_name": "伊伐布雷定", "contraindications": ["急性失代偿心衰"],
     "side_effects": ["心动过缓", "闪光幻觉"], "metabolism": "CYP3A4"},

    # 抗生素补充
    {"id": "penicillin_v", "name": "青霉素V", "category": "青霉素类", "generic_name": "青霉素V钾",
     "contraindications": ["青霉素过敏"], "side_effects": ["过敏反应", "腹泻"], "metabolism": "肾脏排泄"},
    {"id": "ampicillin", "name": "氨苄西林", "category": "青霉素类", "generic_name": "氨苄西林",
     "contraindications": ["青霉素过敏"], "side_effects": ["皮疹", "腹泻", "过敏反应"], "metabolism": "肾脏排泄"},
    {"id": "piperacillin_tazobactam", "name": "哌拉西林他唑巴坦", "category": "青霉素类",
     "generic_name": "哌拉西林钠/他唑巴坦钠",
     "contraindications": ["青霉素过敏"], "side_effects": ["腹泻", "过敏反应"], "metabolism": "肾脏排泄"},
    {"id": "cefazolin", "name": "头孢唑林", "category": "头孢菌素类", "generic_name": "头孢唑林钠",
     "contraindications": ["头孢菌素过敏"], "side_effects": ["过敏反应", "注射部位疼痛"], "metabolism": "肾脏排泄"},
    {"id": "cefadroxil", "name": "头孢羟氨苄", "category": "头孢菌素类", "generic_name": "头孢羟氨苄",
     "contraindications": ["头孢菌素过敏"], "side_effects": ["腹泻", "过敏反应"], "metabolism": "肾脏排泄"},
    {"id": "cefdinir", "name": "头孢地尼", "category": "头孢菌素类", "generic_name": "头孢地尼",
     "contraindications": ["头孢菌素过敏"], "side_effects": ["腹泻", "恶心"], "metabolism": "肾脏排泄"},
    {"id": "cefixime", "name": "头孢克肟", "category": "头孢菌素类", "generic_name": "头孢克肟",
     "contraindications": ["头孢菌素过敏"], "side_effects": ["腹泻", "恶心"], "metabolism": "肾脏排泄"},
    {"id": "cefprozil", "name": "头孢丙烯", "category": "头孢菌素类", "generic_name": "头孢丙烯",
     "contraindications": ["头孢菌素过敏"], "side_effects": ["腹泻", "恶心", "皮疹"], "metabolism": "肾脏排泄"},
    {"id": "cefdinir", "name": "头孢地尼(口服)", "category": "头孢菌素类", "generic_name": "头孢地尼",
     "contraindications": ["头孢菌素过敏"], "side_effects": ["腹泻", "便血(铁剂合用时)"], "metabolism": "肾脏排泄"},
    {"id": "sparfloxacin", "name": "司帕沙星", "category": "喹诺酮类", "generic_name": "司帕沙星",
     "contraindications": ["QT延长"], "side_effects": ["光敏感", "QT延长"], "metabolism": "CYP1A2"},
    {"id": "gemifloxacin", "name": "吉米沙星", "category": "喹诺酮类", "generic_name": "吉米沙星",
     "contraindications": ["QT延长"], "side_effects": ["腹泻", "皮疹"], "metabolism": "部分CYP代谢"},
    {"id": "doxycycline", "name": "多西环素", "category": "四环素类", "generic_name": "盐酸多西环素",
     "contraindications": ["孕妇", "8岁以下儿童"], "side_effects": ["光敏感", "食管溃疡", "牙齿着色"], "metabolism": "肝脏代谢"},
    {"id": "minocycline", "name": "米诺环素", "category": "四环素类", "generic_name": "盐酸米诺环素",
     "contraindications": ["孕妇", "8岁以下儿童"], "side_effects": ["前庭毒性", "牙齿着色", "色素沉着"], "metabolism": "CYP3A4"},
    {"id": "tetracycline", "name": "四环素", "category": "四环素类", "generic_name": "盐酸四环素",
     "contraindications": ["孕妇", "8岁以下儿童", "严重肝功能不全"], "side_effects": ["牙齿着色", "光敏感"], "metabolism": "肾脏排泄"},
    {"id": "azithromycin_iv", "name": "阿奇霉素(注射)", "category": "大环内酯类", "generic_name": "阿奇霉素",
     "contraindications": ["大环内酯类过敏"], "side_effects": ["注射部位反应", "QT延长"], "metabolism": "CYP3A4(少量)"},
    {"id": "roxithromycin", "name": "罗红霉素", "category": "大环内酯类", "generic_name": "罗红霉素",
     "contraindications": ["大环内酯类过敏"], "side_effects": ["恶心", "腹痛"], "metabolism": "CYP3A4"},
    {"id": "mupirocin_nasal", "name": "莫匹罗星(鼻用)", "category": "抗生素(外用)",
     "generic_name": "莫匹罗星", "contraindications": ["对本品过敏"],
     "side_effects": ["鼻出血", "头痛"], "metabolism": "局部代谢"},
    {"id": "polymyxin_b", "name": "多粘菌素B", "category": "多粘菌素类", "generic_name": "硫酸多粘菌素B",
     "contraindications": ["多粘菌素过敏"], "side_effects": ["肾毒性", "神经毒性"], "metabolism": "肾脏排泄"},
    {"id": "quinupristin_dalfopristin", "name": "奎奴普丁/达福普汀", "category": "链阳菌素类",
     "generic_name": "奎奴普丁/达福普汀", "contraindications": ["对本品过敏"],
     "side_effects": ["关节痛", "肌痛", "静脉炎"], "metabolism": "CYP3A4"},
    {"id": "tedizolid", "name": "特地唑胺", "category": "恶唑烷酮类", "generic_name": "磷酸特地唑胺",
     "contraindications": ["对本品过敏"], "side_effects": ["恶心", "头痛"], "metabolism": "磺基转移酶"},
    {"id": "omadacycline", "name": "奥马环素", "category": "甘氨酰环素类", "generic_name": "奥马环素",
     "contraindications": ["对本品过敏"], "side_effects": ["恶心", "呕吐", "光敏感"], "metabolism": "部分肝脏代谢"},
    {"id": "delafloxacin", "name": "地拉沙星", "category": "喹诺酮类", "generic_name": "地拉沙星",
     "contraindications": ["对本品过敏"], "side_effects": ["恶心", "腹泻"], "metabolism": "UGT/醛氧化酶"},
    {"id": "lefamulin", "name": "来法莫林", "category": "截短侧耳素类", "generic_name": "醋酸来法莫林",
     "contraindications": ["CYP3A4强抑制剂合用"], "side_effects": ["恶心", "腹泻", "QT延长"], "metabolism": "CYP3A4"},

    # 精神科补充
    {"id": "lurasidone", "name": "鲁拉西酮", "category": "抗精神病药", "generic_name": "盐酸鲁拉西酮",
     "contraindications": ["CYP3A4强抑制剂/诱导剂合用"], "side_effects": ["嗜睡", "恶心"], "metabolism": "CYP3A4"},
    {"id": "asenapine", "name": "阿塞那平", "category": "抗精神病药", "generic_name": "马来酸阿塞那平",
     "contraindications": ["严重肝功能不全"], "side_effects": ["嗜睡", "头晕", "体重增加"], "metabolism": "UGT1A4/CYP1A2"},
    {"id": "iloperidone", "name": "伊潘立酮", "category": "抗精神病药", "generic_name": "伊潘立酮",
     "contraindications": ["QT延长"], "side_effects": ["QT延长", "体位性低血压"], "metabolism": "CYP2D6/CYP3A4"},
    {"id": "cariprazine", "name": "卡利拉嗪", "category": "抗精神病药", "generic_name": "卡利拉嗪",
     "contraindications": ["CYP3A4强抑制剂合用"], "side_effects": ["锥体外系反应", "失眠"], "metabolism": "CYP3A4"},
    {"id": "brexpiprazole", "name": "布瑞哌唑", "category": "抗精神病药", "generic_name": "布瑞哌唑",
     "contraindications": ["CYP2D6强抑制剂合用(高剂量时)"], "side_effects": ["体重增加", "头痛"], "metabolism": "CYP3A4/CYP2D6"},
    {"id": "pimavanserin", "name": "吡马色林", "category": "抗精神病药", "generic_name": "酒石酸吡马色林",
     "contraindications": ["QT延长"], "side_effects": ["QT延长", "外周水肿"], "metabolism": "CYP3A4"},
    {"id": "fluphenazine", "name": "氟奋乃静", "category": "抗精神病药", "generic_name": "盐酸氟奋乃静",
     "contraindications": ["昏迷", "骨髓抑制"], "side_effects": ["锥体外系反应", "迟发性运动障碍"], "metabolism": "CYP2D6"},
    {"id": "perphenazine", "name": "奋乃静", "category": "抗精神病药", "generic_name": "奋乃静",
     "contraindications": ["昏迷", "骨髓抑制"], "side_effects": ["锥体外系反应", "嗜睡"], "metabolism": "CYP2D6"},
    {"id": "chlorpromazine", "name": "氯丙嗪", "category": "抗精神病药", "generic_name": "盐酸氯丙嗪",
     "contraindications": ["昏迷", "骨髓抑制"], "side_effects": ["体位性低血压", "锥体外系反应", "QT延长"], "metabolism": "CYP2D6/CYP1A2"},
    {"id": "loxapine", "name": "洛沙平", "category": "抗精神病药", "generic_name": "洛沙平",
     "contraindications": ["哮喘", "COPD"], "side_effects": ["支气管痉挛(吸入时)", "锥体外系反应"], "metabolism": "CYP1A2/CYP3A4"},
    {"id": "paliperidone_palmitate", "name": "帕利哌酮棕榈酸酯", "category": "抗精神病药",
     "generic_name": "帕利哌酮棕榈酸酯", "contraindications": ["帕利哌酮过敏"],
     "side_effects": ["注射部位反应", "锥体外系反应"], "metabolism": "CYP2D6(少量)"},
    {"id": "desvenlafaxine", "name": "去甲文拉法辛", "category": "SNRI", "generic_name": "琥珀酸去甲文拉法辛",
     "contraindications": ["MAO抑制剂使用中"], "side_effects": ["恶心", "头晕", "高血压"], "metabolism": "CYP3A4(少量)"},
    {"id": "vilazodone", "name": "维拉佐酮", "category": "SSRI", "generic_name": "盐酸维拉佐酮",
     "contraindications": ["MAO抑制剂使用中"], "side_effects": ["腹泻", "恶心"], "metabolism": "CYP3A4"},
    {"id": "vortioxetine", "name": "沃替西汀", "category": "多模式抗抑郁药", "generic_name": "氢溴酸沃替西汀",
     "contraindications": ["MAO抑制剂使用中"], "side_effects": ["恶心", "头痛"], "metabolism": "CYP2D6"},
    {"id": "selegiline", "name": "司来吉兰", "category": "MAO-B抑制剂", "generic_name": "盐酸司来吉兰",
     "contraindications": ["MAO抑制剂合用", "哌替啶合用"], "side_effects": ["失眠", "恶心", "体位性低血压"], "metabolism": "CYP2B6/CYP2C19"},
    {"id": "rasagiline", "name": "雷沙吉兰", "category": "MAO-B抑制剂", "generic_name": "甲磺酸雷沙吉兰",
     "contraindications": ["MAO抑制剂合用", "哌替啶合用"], "side_effects": ["头痛", "关节痛"], "metabolism": "CYP1A2"},
    {"id": "safinamide", "name": "沙芬酰胺", "category": "MAO-B抑制剂", "generic_name": "甲磺酸沙芬酰胺",
     "contraindications": ["严重肝功能不全"], "side_effects": ["失眠", "恶心"], "metabolism": "CYP3A4/MAO-B"},
    {"id": "pramipexole", "name": "普拉克索", "category": "多巴胺受体激动剂",
     "generic_name": "盐酸普拉克索",
     "contraindications": ["对本品过敏"], "side_effects": ["嗜睡", "幻觉", "体位性低血压"], "metabolism": "不代谢"},
    {"id": "ropinirole", "name": "罗匹尼罗", "category": "多巴胺受体激动剂",
     "generic_name": "盐酸罗匹尼罗",
     "contraindications": ["对本品过敏"], "side_effects": ["嗜睡", "恶心", "幻觉"], "metabolism": "CYP1A2"},
    {"id": "rotigotine", "name": "罗替高汀", "category": "多巴胺受体激动剂",
     "generic_name": "罗替高汀", "contraindications": ["对本品过敏"],
     "side_effects": ["恶心", "嗜睡", "注射部位反应"], "metabolism": "CYP/MAO/COMT"},
    {"id": "entacapone", "name": "恩他卡朋", "category": "COMT抑制剂", "generic_name": "恩他卡朋",
     "contraindications": ["嗜铬细胞瘤"], "side_effects": ["腹泻", "运动障碍加重", "尿液变色"], "metabolism": "CYP3A4/UGT"},
    {"id": "tolcapone", "name": "托卡朋", "category": "COMT抑制剂", "generic_name": "托卡朋",
     "contraindications": ["肝功能不全"], "side_effects": ["肝毒性", "腹泻", "运动障碍加重"], "metabolism": "CYP3A4"},
    {"id": "amantadine", "name": "金刚烷胺", "category": "抗帕金森药", "generic_name": "盐酸金刚烷胺",
     "contraindications": ["严重肾功能不全"], "side_effects": ["幻觉", "网状青斑", "踝部水肿"], "metabolism": "不代谢"},
    {"id": "benztropine", "name": "苯扎托品", "category": "抗胆碱药", "generic_name": "甲磺酸苯扎托品",
     "contraindications": ["闭角型青光眼", "肠梗阻"], "side_effects": ["口干", "便秘", "尿潴留"], "metabolism": "CYP2D6"},
    {"id": "trihexyphenidyl", "name": "苯海索", "category": "抗胆碱药", "generic_name": "盐酸苯海索",
     "contraindications": ["闭角型青光眼", "肠梗阻"], "side_effects": ["口干", "便秘", "尿潴留"], "metabolism": "肝脏代谢"},

    # 内分泌补充
    {"id": "nateglinide", "name": "那格列奈", "category": "格列奈类", "generic_name": "那格列奈",
     "contraindications": ["1型糖尿病"], "side_effects": ["低血糖"], "metabolism": "CYP2C9/CYP3A4"},
    {"id": "exenatide", "name": "艾塞那肽", "category": "GLP-1受体激动剂", "generic_name": "艾塞那肽",
     "contraindications": ["严重肾功能不全", "甲状腺髓样癌史"], "side_effects": ["恶心", "呕吐"], "metabolism": "蛋白水解"},
    {"id": "dulaglutide", "name": "度拉糖肽", "category": "GLP-1受体激动剂", "generic_name": "度拉糖肽",
     "contraindications": ["甲状腺髓样癌史", "MEN2"], "side_effects": ["恶心", "腹泻"], "metabolism": "蛋白水解"},
    {"id": "lixisenatide", "name": "利司那肽", "category": "GLP-1受体激动剂", "generic_name": "利司那肽",
     "contraindications": ["甲状腺髓样癌史"], "side_effects": ["恶心", "呕吐"], "metabolism": "蛋白水解"},
    {"id": "ertugliflozin", "name": "艾托格列净", "category": "SGLT2抑制剂", "generic_name": "艾托格列净",
     "contraindications": ["透析"], "side_effects": ["泌尿生殖感染", "酮症酸中毒"], "metabolism": "UGT1A9/CYP3A4"},
    {"id": "alogliptin", "name": "阿格列汀", "category": "DPP-4抑制剂", "generic_name": "苯甲酸阿格列汀",
     "contraindications": ["心衰(增加住院率)"], "side_effects": ["头痛", "鼻咽炎"], "metabolism": "CYP2D6(少量)"},
    {"id": "gemigliptin", "name": "吉格列汀", "category": "DPP-4抑制剂", "generic_name": "吉格列汀",
     "contraindications": ["对本品过敏"], "side_effects": ["鼻咽炎", "头痛"], "metabolism": "CYP3A4"},
    {"id": "teneligliptin", "name": "替格列汀", "category": "DPP-4抑制剂", "generic_name": "替格列汀",
     "contraindications": ["对本品过敏"], "side_effects": ["便秘", "头痛"], "metabolism": "CYP3A4/黄素单加氧酶"},
    {"id": "insulin_detemir", "name": "地特胰岛素", "category": "胰岛素", "generic_name": "地特胰岛素",
     "contraindications": ["低血糖"], "side_effects": ["低血糖", "体重增加"], "metabolism": "蛋白水解"},
    {"id": "insulin_glulisine", "name": "谷赖胰岛素", "category": "胰岛素", "generic_name": "谷赖胰岛素",
     "contraindications": ["低血糖"], "side_effects": ["低血糖", "注射部位反应"], "metabolism": "蛋白水解"},
    {"id": "insulin_degludec", "name": "德谷胰岛素", "category": "胰岛素", "generic_name": "德谷胰岛素",
     "contraindications": ["低血糖"], "side_effects": ["低血糖", "注射部位反应"], "metabolism": "蛋白水解"},
    {"id": "pramlintide", "name": "普兰林肽", "category": "胰淀素类似物", "generic_name": "醋酸普兰林肽",
     "contraindications": ["胃轻瘫"], "side_effects": ["恶心", "低血糖"], "metabolism": "蛋白水解"},
    {"id": "l-thyroxine", "name": "左甲状腺素(注射)", "category": "甲状腺激素",
     "generic_name": "左甲状腺素钠", "contraindications": ["未治疗的肾上腺功能不全"],
     "side_effects": ["甲亢症状"], "metabolism": "肝脏代谢"},

    # 呼吸补充
    {"id": "indacaterol", "name": "茚达特罗", "category": "β2受体激动剂", "generic_name": "马来酸茚达特罗",
     "contraindications": ["对本品过敏"], "side_effects": ["鼻咽炎", "咳嗽"], "metabolism": "CYP3A4/UGT"},
    {"id": "vilanterol", "name": "维兰特罗", "category": "β2受体激动剂",
     "generic_name": "三苯乙酸维兰特罗",
     "contraindications": ["对本品过敏"], "side_effects": ["头痛", "鼻咽炎"], "metabolism": "CYP3A4"},
    {"id": "umeclidinium", "name": "乌美溴铵", "category": "抗胆碱药", "generic_name": "乌美溴铵",
     "contraindications": ["对阿托品类过敏"], "side_effects": ["口干", "鼻咽炎"], "metabolism": "CYP2D6"},
    {"id": "glycopyrrolate", "name": "格隆溴铵", "category": "抗胆碱药", "generic_name": "格隆溴铵",
     "contraindications": ["闭角型青光眼", "尿潴留"], "side_effects": ["口干", "便秘"], "metabolism": "肾脏排泄"},
    {"id": "roflumilast", "name": "罗氟司特", "category": "PDE4抑制剂", "generic_name": "罗氟司特",
     "contraindications": ["中重度肝功能不全"], "side_effects": ["腹泻", "体重减轻", "恶心"], "metabolism": "CYP3A4/CYP1A2"},
    {"id": "zafirlukast", "name": "扎鲁司特", "category": "白三烯受体拮抗剂",
     "generic_name": "扎鲁司特",
     "contraindications": ["肝功能不全"], "side_effects": ["头痛", "肝毒性"], "metabolism": "CYP2C9"},
    {"id": "zileuton", "name": "齐留通", "category": "5-LOX抑制剂", "generic_name": "齐留通",
     "contraindications": ["活动性肝病", "肝功能不全"], "side_effects": ["肝毒性", "头痛"], "metabolism": "CYP1A2"},
    {"id": "cromolyn_sodium", "name": "色甘酸钠", "category": "肥大细胞稳定剂",
     "generic_name": "色甘酸钠", "contraindications": ["对本品过敏"],
     "side_effects": ["咽喉刺激", "咳嗽"], "metabolism": "不代谢"},
    {"id": "nedocromil", "name": "奈多罗米", "category": "肥大细胞稳定剂",
     "generic_name": "奈多罗米钠", "contraindications": ["对本品过敏"],
     "side_effects": ["头痛", "咽喉刺激"], "metabolism": "不代谢"},

    # 消化补充
    {"id": "vonoprazan", "name": "伏诺拉生", "category": "P-CAB", "generic_name": "富马酸伏诺拉生",
     "contraindications": ["对本品过敏"], "side_effects": ["腹泻", "头痛"], "metabolism": "CYP3A4"},
    {"id": "revaprazan", "name": "瑞伐拉赞", "category": "P-CAB", "generic_name": "盐酸瑞伐拉赞",
     "contraindications": ["对本品过敏"], "side_effects": ["头晕", "腹泻"], "metabolism": "CYP3A4"},
    {"id": "nizatidine", "name": "尼扎替丁", "category": "H2受体拮抗剂", "generic_name": "尼扎替丁",
     "contraindications": ["对本品过敏"], "side_effects": ["头痛", "腹泻"], "metabolism": "CYP2D6(少量)"},
    {"id": "rebamipide", "name": "瑞巴派特", "category": "胃黏膜保护剂", "generic_name": "瑞巴派特",
     "contraindications": ["对本品过敏"], "side_effects": ["便秘", "腹胀"], "metabolism": "部分肝脏代谢"},
    {"id": "teprenone", "name": "替普瑞酮", "category": "胃黏膜保护剂", "generic_name": "替普瑞酮",
     "contraindications": ["对本品过敏"], "side_effects": ["便秘", "腹泻"], "metabolism": "CYP3A4"},
    {"id": "bismuth_subsalicylate", "name": "碱式水杨酸铋", "category": "胃黏膜保护剂",
     "generic_name": "碱式水杨酸铋", "contraindications": ["对水杨酸过敏"],
     "side_effects": ["黑便", "便秘"], "metabolism": "不吸收"},
    {"id": "alosetron", "name": "阿洛司琼", "category": "5-HT3拮抗剂", "generic_name": "盐酸阿洛司琼",
     "contraindications": ["便秘", "炎症性肠病"], "side_effects": ["便秘", "缺血性结肠炎"], "metabolism": "CYP1A2/CYP3A4"},
    {"id": "tegaserod", "name": "替加色罗", "category": "5-HT4激动剂", "generic_name": "马来酸替加色罗",
     "contraindications": ["腹泻型IBS", "胆囊疾病"], "side_effects": ["腹泻", "腹痛"], "metabolism": "CYP1A2"},
    {"id": "lubiprostone", "name": "鲁比前列酮", "category": "ClC-2激活剂",
     "generic_name": "鲁比前列酮", "contraindications": ["机械性肠梗阻"],
     "side_effects": ["恶心", "腹泻"], "metabolism": "CYP(少量)"},
    {"id": "linaclotide", "name": "利那洛肽", "category": "GC-C激动剂", "generic_name": "利那洛肽",
     "contraindications": ["机械性肠梗阻", "儿童(<6岁)"], "side_effects": ["腹泻"], "metabolism": "蛋白水解"},
    {"id": "plecanatide", "name": "普卡那肽", "category": "GC-C激动剂", "generic_name": "普卡那肽",
     "contraindications": ["机械性肠梗阻"], "side_effects": ["腹泻"], "metabolism": "蛋白水解"},
    {"id": "eluxadoline", "name": "艾沙度林", "category": "混合阿片受体调节剂",
     "generic_name": "艾沙度林", "contraindications": ["胆囊切除术后", "胰腺炎"],
     "side_effects": ["便秘", "恶心"], "metabolism": "不代谢"},

    # 镇痛补充
    {"id": "diclofenac", "name": "双氯芬酸", "category": "NSAIDs", "generic_name": "双氯芬酸钠",
     "contraindications": ["活动性消化道溃疡", "CABG围术期"], "side_effects": ["消化道出血", "肝毒性"], "metabolism": "CYP2C9"},
    {"id": "indomethacin", "name": "吲哚美辛", "category": "NSAIDs", "generic_name": "吲哚美辛",
     "contraindications": ["活动性消化道溃疡", "癫痫"], "side_effects": ["消化道出血", "头痛"], "metabolism": "CYP2C9"},
    {"id": "naproxen", "name": "萘普生", "category": "NSAIDs", "generic_name": "萘普生",
     "contraindications": ["活动性消化道溃疡"], "side_effects": ["消化道反应", "头晕"], "metabolism": "CYP2C9"},
    {"id": "etoricoxib", "name": "依托考昔", "category": "COX-2抑制剂", "generic_name": "依托考昔",
     "contraindications": ["活动性消化道溃疡", "严重肝功能不全"], "side_effects": ["心血管事件风险"], "metabolism": "CYP3A4"},
    {"id": "lornoxicam", "name": "氯诺昔康", "category": "NSAIDs", "generic_name": "氯诺昔康",
     "contraindications": ["活动性消化道溃疡"], "side_effects": ["消化道反应"], "metabolism": "CYP2C9"},
    {"id": "dezocine", "name": "地佐辛", "category": "阿片类镇痛药", "generic_name": "地佐辛",
     "contraindications": ["呼吸抑制"], "side_effects": ["恶心", "头晕", "嗜睡"], "metabolism": "肝脏代谢"},
    {"id": "tramadol", "name": "曲马多", "category": "阿片类镇痛药", "generic_name": "盐酸曲马多",
     "contraindications": ["癫痫", "MAO抑制剂使用中"], "side_effects": ["恶心", "头晕", "癫痫风险"], "metabolism": "CYP2D6/CYP3A4"},
    {"id": "morphine", "name": "吗啡", "category": "阿片类镇痛药", "generic_name": "硫酸吗啡",
     "contraindications": ["呼吸抑制", "急性腹痛"], "side_effects": ["呼吸抑制", "便秘", "成瘾"], "metabolism": "UGT2B7"},
    {"id": "hydromorphone", "name": "氢吗啡酮", "category": "阿片类镇痛药",
     "generic_name": "盐酸氢吗啡酮",
     "contraindications": ["呼吸抑制"], "side_effects": ["呼吸抑制", "便秘"], "metabolism": "UGT2B7"},
    {"id": "methadone", "name": "美沙酮", "category": "阿片类镇痛药", "generic_name": "盐酸美沙酮",
     "contraindications": ["呼吸抑制", "QT延长"], "side_effects": ["QT延长", "呼吸抑制", "成瘾"], "metabolism": "CYP2B6/CYP3A4"},

    # 免疫/风湿
    {"id": "sulfasalazine", "name": "柳氮磺吡啶", "category": "DMARD", "generic_name": "柳氮磺吡啶",
     "contraindications": ["磺胺过敏", "肠梗阻"], "side_effects": ["恶心", "皮疹", "骨髓抑制"], "metabolism": "肠道菌群"},
    {"id": "hydroxychloroquine", "name": "羟氯喹", "category": "DMARD", "generic_name": "硫酸羟氯喹",
     "contraindications": ["视网膜病变"], "side_effects": ["视网膜毒性", "QT延长", "低血糖"], "metabolism": "CYP2D6/CYP3A4"},
    {"id": "penicillamine", "name": "青霉胺", "category": "DMARD", "generic_name": "青霉胺",
     "contraindications": ["青霉胺过敏", "严重肾功能不全"], "side_effects": ["肾毒性", "骨髓抑制", "味觉丧失"], "metabolism": "肝脏代谢"},
    {"id": "rituximab", "name": "利妥昔单抗", "category": "生物制剂", "generic_name": "利妥昔单抗",
     "contraindications": ["活动性感染"], "side_effects": ["输液反应", "感染", "乙肝再激活"], "metabolism": "蛋白水解"},
    {"id": "infliximab", "name": "英夫利昔单抗", "category": "生物制剂", "generic_name": "英夫利昔单抗",
     "contraindications": ["活动性感染", "心衰(NYHA III-IV)"], "side_effects": ["感染", "输液反应", "乙肝再激活"], "metabolism": "蛋白水解"},
    {"id": "adalimumab", "name": "阿达木单抗", "category": "生物制剂", "generic_name": "阿达木单抗",
     "contraindications": ["活动性感染"], "side_effects": ["注射部位反应", "感染", "乙肝再激活"], "metabolism": "蛋白水解"},
    {"id": "etanercept", "name": "依那西普", "category": "生物制剂", "generic_name": "依那西普",
     "contraindications": ["活动性感染", "脓毒症"], "side_effects": ["注射部位反应", "感染"], "metabolism": "蛋白水解"},
    {"id": "tocilizumab", "name": "托珠单抗", "category": "生物制剂", "generic_name": "托珠单抗",
     "contraindications": ["活动性感染"], "side_effects": ["感染", "肝毒性", "血脂升高"], "metabolism": "蛋白水解"},
    {"id": "baricitinib", "name": "巴瑞替尼", "category": "JAK抑制剂", "generic_name": "巴瑞替尼",
     "contraindications": ["活动性感染", "严重肝功能不全"], "side_effects": ["感染", "血栓栓塞", "淋巴细胞减少"], "metabolism": "CYP3A4"},
    {"id": "tofacitinib", "name": "托法替布", "category": "JAK抑制剂", "generic_name": "枸橼酸托法替布",
     "contraindications": ["活动性感染"], "side_effects": ["感染", "血栓栓塞", "淋巴细胞减少"], "metabolism": "CYP3A4/CYP2C9"},
    {"id": "upadacitinib", "name": "乌帕替尼", "category": "JAK抑制剂", "generic_name": "乌帕替尼",
     "contraindications": ["活动性感染"], "side_effects": ["感染", "血栓栓塞"], "metabolism": "CYP3A4"},
    {"id": "apremilast", "name": "阿普米司特", "category": "PDE4抑制剂", "generic_name": "阿普米司特",
     "contraindications": ["对本品过敏"], "side_effects": ["腹泻", "恶心", "头痛"], "metabolism": "CYP3A4(少量)"},

    # 眼科补充
    {"id": "dorzolamide", "name": "多佐胺", "category": "碳酸酐酶抑制剂(眼科)",
     "generic_name": "盐酸多佐胺", "contraindications": ["严重肾功能不全"],
     "side_effects": ["眼部烧灼感", "味觉异常"], "metabolism": "CYP2D6(少量)"},
    {"id": "brinzolamide", "name": "布林佐胺", "category": "碳酸酐酶抑制剂(眼科)",
     "generic_name": "布林佐胺", "contraindications": ["严重肾功能不全", "高氯血症性酸中毒"],
     "side_effects": ["视力模糊", "味觉异常"], "metabolism": "CYP3A4"},
    {"id": "dipivefrin", "name": "地匹福林", "category": "拟交感神经药(眼科)",
     "generic_name": "盐酸地匹福林", "contraindications": ["闭角型青光眼"],
     "side_effects": ["眼部刺激", "瞳孔散大"], "metabolism": "酯酶水解"},
    {"id": "apraclonidine", "name": "阿可乐定", "category": "α2受体激动剂(眼科)",
     "generic_name": "盐酸阿可乐定", "contraindications": ["MAO抑制剂使用中"],
     "side_effects": ["眼部过敏", "口干"], "metabolism": "肝脏代谢"},
    {"id": "bimatoprost", "name": "比马前列素", "category": "前列腺素类似物(眼科)",
     "generic_name": "比马前列素", "contraindications": ["对本品过敏"],
     "side_effects": ["虹膜色素加深", "睫毛生长", "眼部刺激"], "metabolism": "酯酶水解"},
    {"id": "travoprost", "name": "曲伏前列素", "category": "前列腺素类似物(眼科)",
     "generic_name": "曲伏前列素", "contraindications": ["对本品过敏"],
     "side_effects": ["虹膜色素加深", "眼部充血"], "metabolism": "酯酶水解"},
    {"id": "tafluprost", "name": "他氟前列素", "category": "前列腺素类似物(眼科)",
     "generic_name": "他氟前列素", "contraindications": ["对本品过敏"],
     "side_effects": ["虹膜色素加深", "眼部刺激"], "metabolism": "酯酶水解"},
    {"id": "netarsudil", "name": "奈舒地尔", "category": "ROCK抑制剂(眼科)",
     "generic_name": "甲磺酸奈舒地尔", "contraindications": ["对本品过敏"],
     "side_effects": ["结膜充血", "角膜沉积"], "metabolism": "酯酶水解"},
    {"id": "pilocarpine_oral", "name": "毛果芸香碱(口服)", "category": "拟胆碱药",
     "generic_name": "硝酸毛果芸香碱", "contraindications": ["哮喘", "虹膜睫状体炎"],
     "side_effects": ["出汗", "流涎", "恶心"], "metabolism": "胆碱酯酶"},

    # 皮肤补充
    {"id": "adapalene", "name": "阿达帕林", "category": "维甲酸类", "generic_name": "阿达帕林",
     "contraindications": ["孕妇"], "side_effects": ["皮肤刺激", "干燥", "光敏感"], "metabolism": "CYP2C9(少量)"},
    {"id": "tazarotene", "name": "他扎罗汀", "category": "维甲酸类", "generic_name": "他扎罗汀",
     "contraindications": ["孕妇"], "side_effects": ["皮肤刺激", "脱皮", "光敏感"], "metabolism": "CYP2C9"},
    {"id": "permethrin", "name": "氯菊酯", "category": "杀虫药(外用)", "generic_name": "氯菊酯",
     "contraindications": ["对本品过敏"], "side_effects": ["局部烧灼感", "瘙痒"], "metabolism": "酯酶水解"},
    {"id": "fluocinonide", "name": "氟轻松", "category": "糖皮质激素(外用)",
     "generic_name": "醋酸氟轻松", "contraindications": ["皮肤感染(单用)"],
     "side_effects": ["皮肤萎缩", "毛细血管扩张"], "metabolism": "肝脏代谢"},
    {"id": "betamethasone_topical", "name": "倍他米松(外用)", "category": "糖皮质激素(外用)",
     "generic_name": "倍他米松", "contraindications": ["皮肤感染(单用)"],
     "side_effects": ["皮肤萎缩", "毛囊炎"], "metabolism": "肝脏代谢"},
    {"id": "clobetasol", "name": "氯倍他索", "category": "糖皮质激素(外用)",
     "generic_name": "丙酸氯倍他索", "contraindications": ["酒糟鼻", "痤疮"],
     "side_effects": ["皮肤萎缩", "下丘脑-垂体轴抑制"], "metabolism": "CYP3A4"},
    {"id": "calcipotriol", "name": "卡泊三醇", "category": "维生素D类似物(外用)",
     "generic_name": "卡泊三醇", "contraindications": ["高钙血症"],
     "side_effects": ["局部刺激", "高钙血症(大面积使用)"], "metabolism": "肝脏代谢"},
    {"id": "imiquimod", "name": "咪喹莫特", "category": "免疫调节剂(外用)",
     "generic_name": "咪喹莫特", "contraindications": ["对本品过敏"],
     "side_effects": ["局部炎症反应", "糜烂"], "metabolism": "局部代谢"},
    {"id": "eflornithine", "name": "依氟鸟氨酸", "category": "外用制剂",
     "generic_name": "盐酸依氟鸟氨酸", "contraindications": ["对本品过敏"],
     "side_effects": ["痤疮", "毛囊炎"], "metabolism": "不代谢"},
    {"id": "crisaborole", "name": "克立硼罗", "category": "PDE4抑制剂(外用)",
     "generic_name": "克立硼罗", "contraindications": ["对本品过敏"],
     "side_effects": ["局部疼痛", "灼热感"], "metabolism": "CYP2C9/3A4"},
    {"id": "ruxolitinib_topical", "name": "鲁索替尼(外用)", "category": "JAK抑制剂(外用)",
     "generic_name": "磷酸鲁索替尼", "contraindications": ["活动性感染"],
     "side_effects": ["局部刺激", "鼻咽炎"], "metabolism": "CYP3A4"},

    # 血液
    {"id": "warfarin_heparin_bridge", "name": "华法林-肝素桥接", "category": "抗凝方案",
     "generic_name": "华法林+肝素", "contraindications": ["活动性出血"],
     "side_effects": ["出血"], "metabolism": "见各成分"},
    {"id": "fondaparinux", "name": "磺达肝癸钠", "category": "抗凝药", "generic_name": "磺达肝癸钠",
     "contraindications": ["严重肾功能不全", "活动性出血"], "side_effects": ["出血", "血小板减少"], "metabolism": "肾脏排泄"},
    {"id": "argatroban", "name": "阿加曲班", "category": "抗凝药", "generic_name": "阿加曲班",
     "contraindications": ["活动性出血"], "side_effects": ["出血", "低血压"], "metabolism": "CYP3A4"},
    {"id": "bivalirudin", "name": "比伐芦定", "category": "抗凝药", "generic_name": "比伐芦定",
     "contraindications": ["活动性出血"], "side_effects": ["出血"], "metabolism": "蛋白酶水解"},
    {"id": "deferoxamine", "name": "去铁胺", "category": "螯合剂", "generic_name": "甲磺酸去铁胺",
     "contraindications": ["严重肾功能不全", "无尿"], "side_effects": ["视听神经毒性", "低血压"], "metabolism": "血浆酶"},
    {"id": "deferasirox", "name": "地拉罗司", "category": "螯合剂", "generic_name": "地拉罗司",
     "contraindications": ["严重肝肾功能不全"], "side_effects": ["肾毒性", "肝毒性", "消化道出血"], "metabolism": "UGT"},
    {"id": "eltrombopag", "name": "艾曲泊帕", "category": "TPO受体激动剂",
     "generic_name": "艾曲泊帕", "contraindications": ["对本品过敏"],
     "side_effects": ["肝毒性", "血栓栓塞", "白内障"], "metabolism": "CYP1A2/2C8"},
    {"id": "romiplostim", "name": "罗米司亭", "category": "TPO受体激动剂",
     "generic_name": "罗米司亭", "contraindications": ["对本品过敏"],
     "side_effects": ["骨髓纤维化", "血栓栓塞"], "metabolism": "蛋白水解"},
    {"id": "emopamil", "name": "依莫帕米", "category": "钙通道阻滞剂",
     "generic_name": "盐酸依莫帕米", "contraindications": ["严重低血压"],
     "side_effects": ["低血压", "头痛"], "metabolism": "CYP3A4"},

    # 杂项补充
    {"id": "dimenhydrinate", "name": "茶苯海明", "category": "抗组胺药", "generic_name": "茶苯海明",
     "contraindications": ["对本品过敏"], "side_effects": ["嗜睡", "口干"], "metabolism": "CYP2D6"},
    {"id": "meclizine", "name": "美克洛嗪", "category": "抗组胺药", "generic_name": "盐酸美克洛嗪",
     "contraindications": ["对本品过敏"], "side_effects": ["嗜睡", "口干"], "metabolism": "CYP2D6"},
    {"id": "scopolamine", "name": "东莨菪碱", "category": "抗胆碱药", "generic_name": "氢溴酸东莨菪碱",
     "contraindications": ["闭角型青光眼", "肠梗阻"], "side_effects": ["口干", "嗜睡", "视力模糊"], "metabolism": "CYP3A4"},
    {"id": "promethazine", "name": "异丙嗪", "category": "抗组胺药", "generic_name": "盐酸异丙嗪",
     "contraindications": ["2岁以下儿童", "昏迷"], "side_effects": ["嗜睡", "QT延长"], "metabolism": "CYP2D6"},
    {"id": "chlorpheniramine", "name": "氯苯那敏", "category": "抗组胺药", "generic_name": "马来酸氯苯那敏",
     "contraindications": ["对本品过敏"], "side_effects": ["嗜睡", "口干"], "metabolism": "CYP2D6"},
    {"id": "cetirizine", "name": "西替利嗪", "category": "抗组胺药", "generic_name": "盐酸西替利嗪",
     "contraindications": ["严重肾功能不全"], "side_effects": ["嗜睡", "头痛", "口干"], "metabolism": "CYP3A4(少量)"},
    {"id": "loratadine", "name": "氯雷他定", "category": "抗组胺药", "generic_name": "氯雷他定",
     "contraindications": ["对本品过敏"], "side_effects": ["头痛", "嗜睡(少见)"], "metabolism": "CYP3A4/CYP2D6"},
    {"id": "fexofenadine", "name": "非索非那定", "category": "抗组胺药", "generic_name": "盐酸非索非那定",
     "contraindications": ["对本品过敏"], "side_effects": ["头痛", "恶心"], "metabolism": "不代谢"},
    {"id": "desloratadine", "name": "地氯雷他定", "category": "抗组胺药", "generic_name": "地氯雷他定",
     "contraindications": ["对本品过敏"], "side_effects": ["头痛", "疲劳"], "metabolism": "CYP3A4/CYP2D6"},
    {"id": "bilastine", "name": "贝他斯汀", "category": "抗组胺药", "generic_name": "贝他斯汀",
     "contraindications": ["对本品过敏"], "side_effects": ["头痛"], "metabolism": "不代谢"},
    {"id": "betahistine", "name": "倍他司汀", "category": "组胺类似物", "generic_name": "甲磺酸倍他司汀",
     "contraindications": ["嗜铬细胞瘤"], "side_effects": ["头痛", "恶心"], "metabolism": "CYP2D6"},
    {"id": "trimipramine", "name": "曲米帕明", "category": "TCA", "generic_name": "马来酸曲米帕明",
     "contraindications": ["心肌梗死恢复期", "QT延长"], "side_effects": ["嗜睡", "口干", "QT延长"], "metabolism": "CYP2C19"},
    {"id": "amitriptyline", "name": "阿米替林", "category": "TCA", "generic_name": "盐酸阿米替林",
     "contraindications": ["心肌梗死恢复期", "QT延长"], "side_effects": ["嗜睡", "口干", "便秘", "QT延长"], "metabolism": "CYP2D6/CYP2C19"},
    {"id": "nortriptyline", "name": "去甲替林", "category": "TCA", "generic_name": "盐酸去甲替林",
     "contraindications": ["心肌梗死恢复期"], "side_effects": ["嗜睡", "口干", "QT延长"], "metabolism": "CYP2D6"},
    {"id": "imipramine", "name": "丙咪嗪", "category": "TCA", "generic_name": "盐酸丙咪嗪",
     "contraindications": ["心肌梗死恢复期"], "side_effects": ["嗜睡", "口干", "体位性低血压"], "metabolism": "CYP2D6/CYP2C19"},
    {"id": "doxepin", "name": "多塞平", "category": "TCA", "generic_name": "盐酸多塞平",
     "contraindications": ["青光眼", "尿潴留"], "side_effects": ["嗜睡", "口干"], "metabolism": "CYP2D6/CYP2C19"},
    {"id": "clomipramine", "name": "氯米帕明", "category": "TCA", "generic_name": "盐酸氯米帕明",
     "contraindications": ["MAO抑制剂使用中"], "side_effects": ["嗜睡", "口干", "QT延长"], "metabolism": "CYP2D6/CYP2C19"},
    {"id": "mianserin", "name": "米安色林", "category": "NaSSA", "generic_name": "盐酸米安色林",
     "contraindications": ["躁狂症"], "side_effects": ["嗜睡", "体重增加"], "metabolism": "CYP2D6"},
    {"id": "agomelatine", "name": "阿戈美拉汀", "category": "MT1/MT2激动剂",
     "generic_name": "阿戈美拉汀", "contraindications": ["肝功能不全"],
     "side_effects": ["恶心", "头晕", "肝毒性"], "metabolism": "CYP1A2"},
]

# ========== 第二批交互 ==========
MORE_INTERACTIONS = [
    # ARB+ACEI
    ("irbesartan", "lisinopril", "high", "ACEI+ARB双重RAAS阻断"),
    ("candesartan", "enalapril", "high", "ACEI+ARB双重RAAS阻断"),
    ("telmisartan", "ramipril", "high", "ACEI+ARB双重RAAS阻断"),
    ("olmesartan", "lisinopril", "high", "ACEI+ARB双重RAAS阻断"),
    ("azilsartan", "enalapril", "high", "ACEI+ARB双重RAAS阻断"),

    # 更多 CYP 抑制
    ("fluoxetine", "amitriptyline", "high", "氟西汀抑制CYP2D6,阿米替林血药浓度升高"),
    ("paroxetine", "amitriptyline", "high", "帕罗西汀抑制CYP2D6,阿米替林血药浓度升高"),
    ("fluoxetine", "imipramine", "high", "氟西汀抑制CYP2D6,丙咪嗪血药浓度升高"),
    ("fluoxetine", "nortriptyline", "high", "氟西汀抑制CYP2D6,去甲替林血药浓度升高"),
    ("paroxetine", "nortriptyline", "high", "帕罗西汀抑制CYP2D6,去甲替林血药浓度升高"),
    ("fluoxetine", "codeine", "high", "氟西汀抑制CYP2D6,可待因无法转化为吗啡"),
    ("paroxetine", "codeine", "high", "帕罗西汀抑制CYP2D6,可待因无法转化为吗啡"),
    ("fluoxetine", "tramadol", "critical", "SSRI+阿片,5-HT综合征+癫痫风险"),
    ("sertraline", "amitriptyline", "medium", "舍曲林轻度抑制CYP2D6,阿米替林血药浓度可能升高"),

    # TCA + 其他
    ("amitriptyline", "fluoxetine", "high", "氟西汀抑制CYP2D6,阿米替林血药浓度升高"),
    ("amitriptyline", "paroxetine", "high", "帕罗西汀抑制CYP2D6,阿米替林血药浓度升高"),
    ("amitriptyline", "cimetidine", "high", "西咪替丁抑制CYP,阿米替林代谢减慢"),
    ("amitriptyline", "MAO_inhibitors", "critical", "TCA+MAO抑制剂,高血压危象/5-HT综合征"),
    ("imipramine", "MAO_inhibitors", "critical", "TCA+MAO抑制剂,高血压危象"),
    ("clomipramine", "MAO_inhibitors", "critical", "TCA+MAO抑制剂,5-HT综合征风险极高"),
    ("clomipramine", "sertraline", "high", "双重5-HT再摄取抑制"),
    ("clomipramine", "fluoxetine", "high", "双重5-HT再摄取抑制+氟西汀抑制CYP2D6"),

    # 多巴胺激动剂
    ("pramipexole", "cimetidine", "medium", "西咪替丁降低普拉克索肾脏清除"),
    ("ropinirole", "ciprofloxacin", "medium", "环丙沙星抑制CYP1A2,罗匹尼罗血药浓度升高"),
    ("selegiline", "fluoxetine", "critical", "MAO-B抑制剂+SSRI,5-HT综合征风险(需停药5周)"),
    ("selegiline", "sertraline", "critical", "MAO-B抑制剂+SSRI,5-HT综合征风险"),
    ("selegiline", "tramadol", "high", "MAO抑制+阿片,5-HT综合征/癫痫风险"),
    ("rasagiline", "fluoxetine", "critical", "MAO-B抑制剂+SSRI,5-HT综合征风险"),
    ("rasagiline", "dextromethorphan", "high", "MAO抑制+右美沙芬,5-HT综合征风险"),

    # 抗疟/抗炎
    ("hydroxychloroquine", "digoxin", "medium", "羟氯喹升高地高辛血药浓度"),
    ("hydroxychloroquine", "methotrexate", "medium", "可能增加甲氨蝶呤毒性"),
    ("sulfasalazine", "warfarin", "medium", "柳氮磺吡啶增强华法林抗凝效果"),
    ("sulfasalazine", "digoxin", "medium", "柳氮磺吡啶降低地高辛吸收"),

    # JAK抑制剂
    ("tofacitinib", "fluconazole", "high", "氟康唑抑制CYP3A4,托法替布血药浓度升高"),
    ("tofacitinib", "rifampicin", "high", "利福平诱导CYP3A4,托法替布效果降低"),
    ("baricitinib", "rifampicin", "high", "利福平诱导CYP3A4,巴瑞替尼效果降低"),

    # 生物制剂
    ("infliximab", "anakinra", "high", "双重免疫抑制,感染风险显著增加"),
    ("infliximab", "abatacept", "high", "双重免疫抑制,感染风险显著增加"),
    ("adalimumab", "anakinra", "high", "双重免疫抑制,感染风险显著增加"),
    ("rituximab", "cisplatin", "high", "双重肾毒性"),
    ("tocilizumab", "simvastatin", "medium", "托珠单抗降低CYP3A4活性,他汀代谢可能受影响"),

    # 眼科
    ("timolol_eye", "verapamil", "high", "β阻滞剂全身吸收+维拉帕米,心动过缓风险"),
    ("timolol_eye", "propranolol", "medium", "双重β阻滞,全身不良反应增加"),
    ("brimonidine", "MAO_inhibitors", "high", "α2激动剂+MAO抑制剂"),
    ("latanoprost", "timolol_eye", "medium", "联合使用降眼压效果增强"),

    # 抗组胺药
    ("cetirizine", "diazepam", "medium", "双重中枢抑制"),
    ("hydroxyzine", "diazepam", "high", "双重中枢抑制"),
    ("promethazine", "diazepam", "high", "双重中枢抑制"),
    ("loratadine", "ketoconazole", "medium", "酮康唑抑制CYP3A4,氯雷他定血药浓度升高"),
    ("loratadine", "erythromycin", "medium", "红霉素抑制CYP3A4,氯雷他定血药浓度升高"),

    # 皮肤
    ("isotretinoin", "tetracycline", "critical", "维甲酸+四环素,假性脑瘤风险极高"),
    ("isotretinoin", "doxycycline", "critical", "维甲酸+四环素,假性脑瘤风险"),
    ("isotretinoin", "minocycline", "critical", "维甲酸+四环素,假性脑瘤风险"),
    ("isotretinoin", "vitamin_a", "high", "维甲酸+维生素A,维生素A过多症"),
    ("tretinoin", "tetracycline", "high", "维A酸+四环素,假性脑瘤风险"),
    ("tretinoin", "ketoconazole", "medium", "酮康唑抑制CYP2C9,维A酸血药浓度升高"),

    # 血液
    ("fondaparinux", "aspirin", "high", "抗凝+抗血小板,出血风险增加"),
    ("fondaparinux", "NSAIDs", "high", "抗凝+NSAIDs,出血风险增加"),
    ("eltrombopag", "antacids", "medium", "含多价阳离子抗酸剂降低艾曲泊帕吸收"),
    ("eltrombopag", "rosuvastatin", "medium", "艾曲泊帕抑制OATP1B1,瑞舒伐他汀暴露量增加"),
    ("deferasirox", "repaglinide", "medium", "地拉罗司诱导CYP2C8,瑞格列奈效果降低"),
    ("argatroban", "warfarin", "high", "双重抗凝,出血风险(需监测INR)"),
    ("bivalirudin", "aspirin", "high", "抗凝+抗血小板"),

    # 其他
    ("hydroxychloroquine", "amiodarone", "high", "双重QT延长"),
    ("hydroxychloroquine", "haloperidol", "high", "双重QT延长"),
    ("amantadine", "hydrochlorothiazide", "medium", "噻嗪类利尿剂降低金刚烷胺肾脏清除"),
    ("amantadine", "trimethoprim", "medium", "甲氧苄啶降低金刚烷胺肾脏清除"),
    ("scopolamine", "amitriptyline", "high", "双重抗胆碱效应"),
    ("promethazine", "amitriptyline", "high", "双重抗胆碱效应+QT延长"),
    ("dimenhydrinate", "amitriptyline", "high", "双重抗胆碱效应"),
    ("tramadol", "amitriptyline", "high", "阿片+TCA,5-HT综合征+癫痫风险"),
    ("tramadol", "sertraline", "critical", "阿片+SSRI,5-HT综合征风险"),
    ("methadone", "fluoxetine", "high", "氟西汀抑制CYP2D6,美沙酮血药浓度可能升高"),
    ("methadone", "fluconazole", "high", "氟康唑抑制CYP3A4,美沙酮血药浓度升高"),
    ("methadone", "amiodarone", "high", "双重QT延长"),
    ("hydromorphone", "diazepam", "critical", "阿片+苯二氮卓,呼吸抑制风险极高"),
    ("morphine", "diazepam", "critical", "阿片+苯二氮卓,呼吸抑制风险极高"),
    ("morphine", "gabapentin", "medium", "双重中枢抑制"),
    ("baclofen", "morphine", "high", "双重中枢抑制,呼吸抑制风险"),
]

# ========== 第二批替代药物 ==========
MORE_ALTERNATIVES = [
    ("warfarin", "edoxaban", "新型口服抗凝药,每日一次"),
    ("simvastatin", "pitavastatin", "匹伐他汀不经CYP3A4代谢"),
    ("amlodipine", "felodipine", "非洛地平作用相似"),
    ("lisinopril", "perindopril", "培哚普利循证证据充分"),
    ("metformin", "liraglutide", "GLP-1受体激动剂有减重和心血管获益"),
    ("metformin", "semaglutide", "司美格鲁肽有显著心血管和减重获益"),
    ("glimepiride", "empagliflozin", "SGLT2抑制剂有心血管保护"),
    ("omeprazole", "vonoprazan", "P-CAB抑酸更快更强"),
    ("fluoxetine", "vortioxetine", "沃替西汀多模式作用,性功能副作用少"),
    ("amitriptyline", "duloxetine", "SNRI替代TCA,心脏毒性低"),
    ("amitriptyline", "venlafaxine", "SNRI替代TCA"),
    ("diazepam", "oxazepam", "奥沙西泮仅经葡萄糖醛酸化,老年患者首选"),
    ("morphine", "oxycodone", "羟考酮口服生物利用度高"),
    ("morphine", "hydromorphone", "氢吗啡酮肾毒性代谢物少"),
    ("ciprofloxacin", "levofloxacin", "左氧氟沙星CYP1A2抑制较弱"),
    ("ketoconazole", "fluconazole", "氟康唑肝毒性相对较低"),
    ("doxorubicin", "liposomal_doxorubicin", "脂质体多柔比星心脏毒性低"),
    ("cisplatin", "carboplatin", "卡铂肾毒性和耳毒性较低"),
]

# ========== 去重并追加 ==========
new_drugs = [d for d in MORE_DRUGS if d["id"] not in existing_ids]
new_interactions = [(a, b, s, m) for a, b, s, m in MORE_INTERACTIONS
                    if (a, b) not in existing_interactions]

print(f"Second batch - New drugs: {len(new_drugs)}, New interactions: {len(new_interactions)}")

# 追加到文件
with open("app/graph/drug_data.py", "r", encoding="utf-8") as f:
    content = f.read()

addition = f"""
# ==================== 第二批扩展药物 ====================
_EXTRA_DRUGS_2 = {repr(new_drugs)}
DRUGS.extend(_EXTRA_DRUGS_2)

_EXTRA_INTERACTIONS_2 = {repr(new_interactions)}
INTERACTIONS.extend(_EXTRA_INTERACTIONS_2)

_EXTRA_ALTERNATIVES_2 = {repr(MORE_ALTERNATIVES)}
ALTERNATIVES.extend(_EXTRA_ALTERNATIVES_2)

"""

marker = "\ndef build_graph_from_data():"
content = content.replace(marker, addition + marker)

with open("app/graph/drug_data.py", "w", encoding="utf-8") as f:
    f.write(content)

# 验证
importlib.reload(dd)
ids = {d["id"] for d in dd.DRUGS}
print(f"Final: {len(dd.DRUGS)} drugs ({len(ids)} unique), {len(dd.INTERACTIONS)} interactions, {len(dd.ALTERNATIVES)} alternatives")
