"""扩展药物数据脚本:新增300+药物和300+交互。"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# 读取当前文件
with open("app/graph/drug_data.py", "r", encoding="utf-8") as f:
    content = f.read()

# ========== 新增药物 ==========
EXTRA_DRUGS = [
    # ==================== 心血管(续) ====================
    {"id": "propranolol", "name": "普萘洛尔", "category": "β受体阻滞剂", "generic_name": "盐酸普萘洛尔",
     "contraindications": ["哮喘", "窦性心动过缓", "心源性休克"],
     "side_effects": ["心动过缓", "支气管痉挛", "疲劳"], "metabolism": "CYP2D6/CYP1A2"},
    {"id": "nebivolol", "name": "奈比洛尔", "category": "β受体阻滞剂", "generic_name": "奈比洛尔",
     "contraindications": ["肝功能不全", "心源性休克", "窦性心动过缓"],
     "side_effects": ["头痛", "疲劳", "低血压"], "metabolism": "CYP2D6"},
    {"id": "labetalol", "name": "拉贝洛尔", "category": "α/β受体阻滞剂", "generic_name": "盐酸拉贝洛尔",
     "contraindications": ["哮喘", "II-III度房室传导阻滞", "心源性休克"],
     "side_effects": ["低血压", "头晕", "疲劳"], "metabolism": "葡萄糖醛酸结合"},
    {"id": "nicardipine", "name": "尼卡地平", "category": "钙通道阻滞剂", "generic_name": "盐酸尼卡地平",
     "contraindications": ["严重主动脉瓣狭窄", "颅内出血急性期"],
     "side_effects": ["头痛", "水肿", "心动过速"], "metabolism": "CYP3A4"},
    {"id": "felodipine", "name": "非洛地平", "category": "钙通道阻滞剂", "generic_name": "非洛地平",
     "contraindications": ["心源性休克", "严重低血压"],
     "side_effects": ["水肿", "头痛", "面部潮红"], "metabolism": "CYP3A4"},
    {"id": "lercanidipine", "name": "乐卡地平", "category": "钙通道阻滞剂", "generic_name": "盐酸乐卡地平",
     "contraindications": ["未控制的心衰", "严重肝肾功能不全"],
     "side_effects": ["水肿", "头痛", "面部潮红"], "metabolism": "CYP3A4"},
    {"id": "nitroprusside", "name": "硝普钠", "category": "血管扩张药", "generic_name": "硝普钠",
     "contraindications": ["代偿性高血压", "颅内压升高"],
     "side_effects": ["低血压", "氰化物中毒"], "metabolism": "红细胞代谢"},
    {"id": "hydralazine", "name": "肼屈嗪", "category": "血管扩张药", "generic_name": "盐酸肼屈嗪",
     "contraindications": ["冠心病", "主动脉夹层", "系统性红斑狼疮"],
     "side_effects": ["狼疮样综合征", "心动过速", "头痛"], "metabolism": "NAT2乙酰化"},
    {"id": "minoxidil", "name": "米诺地尔", "category": "血管扩张药", "generic_name": "米诺地尔",
     "contraindications": ["嗜铬细胞瘤"],
     "side_effects": ["多毛症", "液体潴留", "心动过速"], "metabolism": "葡萄糖醛酸结合"},
    {"id": "isosorbide_dinitrate", "name": "硝酸异山梨酯", "category": "抗心绞痛药",
     "generic_name": "硝酸异山梨酯",
     "contraindications": ["严重低血压", "肥厚型梗阻性心肌病", "PDE5抑制剂使用中"],
     "side_effects": ["头痛", "低血压", "耐药性"], "metabolism": "肝脏代谢"},
    {"id": "trimetazidine", "name": "曲美他嗪", "category": "抗心绞痛药", "generic_name": "盐酸曲美他嗪",
     "contraindications": ["帕金森病", "震颤", "严重肾功能不全"],
     "side_effects": ["震颤", "帕金森样症状", "头晕"], "metabolism": "肾脏排泄"},
    {"id": "ivabradine", "name": "伊伐布雷定", "category": "抗心绞痛药", "generic_name": "伊伐布雷定",
     "contraindications": ["窦性心动过缓", "病态窦房结综合征", "严重肝功能不全"],
     "side_effects": ["闪光幻觉", "心动过缓"], "metabolism": "CYP3A4"},
    {"id": "ranolazine", "name": "雷诺嗪", "category": "抗心绞痛药", "generic_name": "雷诺嗪",
     "contraindications": ["肝功能不全", "QT间期延长"],
     "side_effects": ["头晕", "便秘", "QT延长"], "metabolism": "CYP3A4/CYP2D6"},
    {"id": "moxonidine", "name": "莫索尼定", "category": "中枢降压药", "generic_name": "盐酸莫索尼定",
     "contraindications": ["病态窦房结综合征", "严重心动过缓", "严重心衰"],
     "side_effects": ["口干", "头晕", "疲乏"], "metabolism": "部分肝脏代谢"},
    {"id": "clonidine", "name": "可乐定", "category": "中枢降压药", "generic_name": "盐酸可乐定",
     "contraindications": ["严重心动过缓", "病态窦房结综合征"],
     "side_effects": ["口干", "嗜睡", "反跳性高血压"], "metabolism": "50%肝脏代谢"},
    {"id": "methyldopa", "name": "甲基多巴", "category": "中枢降压药", "generic_name": "甲基多巴",
     "contraindications": ["活动性肝病", "嗜铬细胞瘤"],
     "side_effects": ["嗜睡", "肝损害", "溶血性贫血"], "metabolism": "肝脏代谢"},

    # ==================== 抗心律失常 ====================
    {"id": "flecainide", "name": "氟卡尼", "category": "抗心律失常药", "generic_name": "醋酸氟卡尼",
     "contraindications": ["结构性心脏病", "心衰", "束支传导阻滞"],
     "side_effects": ["心律失常加重", "头晕", "视觉障碍"], "metabolism": "CYP2D6"},
    {"id": "propafenone", "name": "普罗帕酮", "category": "抗心律失常药", "generic_name": "盐酸普罗帕酮",
     "contraindications": ["心衰", "严重心动过缓", "哮喘"],
     "side_effects": ["心律失常加重", "金属味", "恶心"], "metabolism": "CYP2D6/CYP1A2"},
    {"id": "sotalol", "name": "索他洛尔", "category": "抗心律失常药", "generic_name": "盐酸索他洛尔",
     "contraindications": ["哮喘", "窦性心动过缓", "QT延长", "心源性休克"],
     "side_effects": ["心动过缓", "QT延长", "疲劳"], "metabolism": "肾脏排泄"},
    {"id": "dronedarone", "name": "决奈达隆", "category": "抗心律失常药", "generic_name": "盐酸决奈达隆",
     "contraindications": ["永久性房颤", "严重肝损害", "NYHA IV级心衰"],
     "side_effects": ["QT延长", "肝毒性", "心动过缓"], "metabolism": "CYP3A4"},
    {"id": "lidocaine_iv", "name": "利多卡因(注射)", "category": "抗心律失常药",
     "generic_name": "盐酸利多卡因",
     "contraindications": ["严重窦房传导阻滞", "WPW综合征"],
     "side_effects": ["中枢神经毒性", "低血压", "癫痫"], "metabolism": "CYP1A2/CYP3A4"},

    # ==================== 心衰药物 ====================
    {"id": "sacubitril_valsartan", "name": "沙库巴曲缬沙坦", "category": "ARNI",
     "generic_name": "沙库巴曲缬沙坦",
     "contraindications": ["ACEI/ARB过敏", "血管性水肿史", "孕妇"],
     "side_effects": ["低血压", "高钾血症", "肾功能恶化"], "metabolism": "酯酶水解"},
    {"id": "spironolactone", "name": "螺内酯", "category": "利尿药", "generic_name": "螺内酯",
     "contraindications": ["高钾血症", "严重肾功能不全", "Addison病"],
     "side_effects": ["高钾血症", "男性乳房发育", "月经不调"], "metabolism": "肝脏代谢"},
    {"id": "eplerenone", "name": "依普利酮", "category": "利尿药", "generic_name": "依普利酮",
     "contraindications": ["高钾血症", "严重肾功能不全", "CYP3A4强抑制剂合用"],
     "side_effects": ["高钾血症", "头晕", "腹泻"], "metabolism": "CYP3A4"},
    {"id": "torasemide", "name": "托拉塞米", "category": "利尿药", "generic_name": "托拉塞米",
     "contraindications": ["无尿", "严重低钾血症", "肝昏迷"],
     "side_effects": ["低钾血症", "低血压", "高尿酸血症"], "metabolism": "CYP2C9"},
    {"id": "mannitol", "name": "甘露醇", "category": "利尿药", "generic_name": "甘露醇",
     "contraindications": ["严重肾功能不全", "颅内活动性出血", "严重脱水"],
     "side_effects": ["电解质紊乱", "肺水肿", "肾损害"], "metabolism": "肾脏排泄"},

    # ==================== 降脂药 ====================
    {"id": "rosuvastatin", "name": "瑞舒伐他汀", "category": "他汀类", "generic_name": "瑞舒伐他汀钙",
     "contraindications": ["活动性肝病", "孕妇", "哺乳期"],
     "side_effects": ["肌痛", "转氨酶升高", "血糖升高"], "metabolism": "CYP2C9(少量)"},
    {"id": "pravastatin", "name": "普伐他汀", "category": "他汀类", "generic_name": "普伐他汀钠",
     "contraindications": ["活动性肝病", "孕妇"],
     "side_effects": ["肌痛", "消化不良", "转氨酶升高"], "metabolism": "不经过CYP450"},
    {"id": "pitavastatin", "name": "匹伐他汀", "category": "他汀类", "generic_name": "匹伐他汀钙",
     "contraindications": ["活动性肝病", "孕妇", "哺乳期"],
     "side_effects": ["肌痛", "转氨酶升高"], "metabolism": "CYP2C9(少量)"},
    {"id": "ezetimibe", "name": "依折麦布", "category": "降脂药", "generic_name": "依折麦布",
     "contraindications": ["活动性肝病"],
     "side_effects": ["腹痛", "腹泻", "转氨酶升高"], "metabolism": "葡萄糖醛酸结合"},
    {"id": "fenofibrate", "name": "非诺贝特", "category": "贝特类", "generic_name": "非诺贝特",
     "contraindications": ["严重肝肾功能不全", "胆囊疾病"],
     "side_effects": ["肌痛", "转氨酶升高", "胆石症"], "metabolism": "酯酶水解/CYP3A4"},
    {"id": "cholestyramine", "name": "考来烯胺", "category": "胆酸螯合剂", "generic_name": "考来烯胺",
     "contraindications": ["完全性胆道梗阻"],
     "side_effects": ["便秘", "腹胀", "脂肪吸收不良"], "metabolism": "不吸收"},
    {"id": "PCSK9_inhibitor", "name": "依洛尤单抗", "category": "PCSK9抑制剂",
     "generic_name": "依洛尤单抗",
     "contraindications": ["对本品过敏"],
     "side_effects": ["注射部位反应", "上呼吸道感染"], "metabolism": "蛋白水解"},
    {"id": "bempedoic_acid", "name": "贝派地酸", "category": "降脂药", "generic_name": "贝派地酸",
     "contraindications": ["痛风", "高尿酸血症"],
     "side_effects": ["高尿酸血症", "肌痛", "贫血"], "metabolism": "ACSVL1活化"},

    # ==================== 更多抗生素 ====================
    {"id": "ceftriaxone", "name": "头孢曲松", "category": "头孢菌素类", "generic_name": "头孢曲松钠",
     "contraindications": ["新生儿高胆红素血症", "早产儿", "过敏"],
     "side_effects": ["胆汁淤积", "过敏反应", "腹泻"], "metabolism": "不代谢"},
    {"id": "cefepime", "name": "头孢吡肟", "category": "头孢菌素类", "generic_name": "盐酸头孢吡肟",
     "contraindications": ["头孢菌素过敏"],
     "side_effects": ["神经毒性", "癫痫", "腹泻"], "metabolism": "肾脏排泄"},
    {"id": "cefuroxime", "name": "头孢呋辛", "category": "头孢菌素类", "generic_name": "头孢呋辛酯",
     "contraindications": ["头孢菌素过敏"],
     "side_effects": ["腹泻", "恶心", "过敏反应"], "metabolism": "肾脏排泄"},
    {"id": "ceftazidime", "name": "头孢他啶", "category": "头孢菌素类", "generic_name": "头孢他啶",
     "contraindications": ["头孢菌素过敏"],
     "side_effects": ["腹泻", "过敏反应"], "metabolism": "肾脏排泄"},
    {"id": "cefoperazone", "name": "头孢哌酮", "category": "头孢菌素类", "generic_name": "头孢哌酮钠",
     "contraindications": ["头孢菌素过敏", "严重出血倾向"],
     "side_effects": ["出血", "腹泻", "过敏反应"], "metabolism": "胆汁排泄为主"},
    {"id": "cefotaxime", "name": "头孢噻肟", "category": "头孢菌素类", "generic_name": "头孢噻肟钠",
     "contraindications": ["头孢菌素过敏"],
     "side_effects": ["注射部位疼痛", "腹泻", "过敏"], "metabolism": "肝脏去乙酰化"},
    {"id": "moxifloxacin", "name": "莫西沙星", "category": "喹诺酮类", "generic_name": "盐酸莫西沙星",
     "contraindications": ["QT间期延长", "重症肌无力", "肝功能不全"],
     "side_effects": ["QT延长", "恶心", "头晕"], "metabolism": "CYP1A2(部分)"},
    {"id": "levofloxacin", "name": "左氧氟沙星", "category": "喹诺酮类", "generic_name": "左氧氟沙星",
     "contraindications": ["癫痫", "重症肌无力", "QT间期延长"],
     "side_effects": ["肌腱炎", "QT延长", "血糖异常"], "metabolism": "肾脏排泄"},
    {"id": "norfloxacin", "name": "诺氟沙星", "category": "喹诺酮类", "generic_name": "诺氟沙星",
     "contraindications": ["儿童青少年", "癫痫"],
     "side_effects": ["恶心", "头痛", "光敏感"], "metabolism": "CYP1A2"},
    {"id": "meropenem", "name": "美罗培南", "category": "碳青霉烯类", "generic_name": "美罗培南",
     "contraindications": ["碳青霉烯过敏"],
     "side_effects": ["腹泻", "恶心", "注射部位炎症"], "metabolism": "肾脏排泄"},
    {"id": "ertapenem", "name": "厄他培南", "category": "碳青霉烯类", "generic_name": "厄他培南钠",
     "contraindications": ["碳青霉烯过敏"],
     "side_effects": ["腹泻", "头痛", "静脉炎"], "metabolism": "肾脏排泄"},
    {"id": "gentamicin", "name": "庆大霉素", "category": "氨基糖苷类", "generic_name": "硫酸庆大霉素",
     "contraindications": ["氨基糖苷类过敏", "重症肌无力"],
     "side_effects": ["肾毒性", "耳毒性"], "metabolism": "肾脏排泄"},
    {"id": "amikacin", "name": "阿米卡星", "category": "氨基糖苷类", "generic_name": "硫酸阿米卡星",
     "contraindications": ["氨基糖苷类过敏"],
     "side_effects": ["肾毒性", "耳毒性"], "metabolism": "肾脏排泄"},
    {"id": "tobramycin", "name": "妥布霉素", "category": "氨基糖苷类", "generic_name": "硫酸妥布霉素",
     "contraindications": ["氨基糖苷类过敏"],
     "side_effects": ["肾毒性", "耳毒性"], "metabolism": "肾脏排泄"},
    {"id": "vancomycin", "name": "万古霉素", "category": "糖肽类", "generic_name": "盐酸万古霉素",
     "contraindications": ["万古霉素过敏"],
     "side_effects": ["红人综合征", "肾毒性", "耳毒性"], "metabolism": "肾脏排泄"},
    {"id": "teicoplanin", "name": "替考拉宁", "category": "糖肽类", "generic_name": "替考拉宁",
     "contraindications": ["替考拉宁过敏"],
     "side_effects": ["注射部位反应", "肝肾毒性"], "metabolism": "肾脏排泄"},
    {"id": "linezolid", "name": "利奈唑胺", "category": "恶唑烷酮类", "generic_name": "利奈唑胺",
     "contraindications": ["MAO抑制剂使用中", "嗜铬细胞瘤"],
     "side_effects": ["骨髓抑制", "乳酸酸中毒", "5-HT综合征"], "metabolism": "非CYP氧化"},
    {"id": "daptomycin", "name": "达托霉素", "category": "脂肽类", "generic_name": "达托霉素",
     "contraindications": ["达托霉素过敏"],
     "side_effects": ["CK升高", "横纹肌溶解"], "metabolism": "肾脏排泄"},
    {"id": "tigecycline", "name": "替加环素", "category": "甘氨酰环素类", "generic_name": "替加环素",
     "contraindications": ["替加环素过敏"],
     "side_effects": ["恶心", "呕吐", "死亡率增加"], "metabolism": "肝脏代谢"},
    {"id": "aztreonam", "name": "氨曲南", "category": "单环β-内酰胺类", "generic_name": "氨曲南",
     "contraindications": ["氨曲南过敏"],
     "side_effects": ["注射部位反应", "腹泻", "皮疹"], "metabolism": "肾脏排泄"},
    {"id": "colistin", "name": "多粘菌素E", "category": "多粘菌素类", "generic_name": "硫酸多粘菌素E",
     "contraindications": ["重症肌无力"],
     "side_effects": ["肾毒性", "神经毒性"], "metabolism": "肾脏排泄"},
    {"id": "nitrofurantoin", "name": "呋喃妥因", "category": "硝基呋喃类", "generic_name": "呋喃妥因",
     "contraindications": ["肾功能不全(GFR<30)", "G6PD缺乏"],
     "side_effects": ["肺纤维化", "肝毒性", "周围神经病变"], "metabolism": "肝脏代谢"},
    {"id": "metronidazole", "name": "甲硝唑", "category": "硝基咪唑类", "generic_name": "甲硝唑",
     "contraindications": ["第一孕期", "血液病"],
     "side_effects": ["金属味", "恶心", "周围神经病变"], "metabolism": "CYP2C9/CYP3A4"},
    {"id": "tinidazole", "name": "替硝唑", "category": "硝基咪唑类", "generic_name": "替硝唑",
     "contraindications": ["第一孕期", "血液病"],
     "side_effects": ["金属味", "恶心", "头痛"], "metabolism": "CYP3A4"},
    {"id": "clindamycin", "name": "克林霉素", "category": "林可酰胺类", "generic_name": "盐酸克林霉素",
     "contraindications": ["克林霉素过敏", "溃疡性结肠炎"],
     "side_effects": ["艰难梭菌肠炎", "皮疹"], "metabolism": "CYP3A4"},
    {"id": "cotrimoxazole", "name": "复方磺胺甲恶唑", "category": "磺胺类",
     "generic_name": "磺胺甲恶唑/甲氧苄啶",
     "contraindications": ["磺胺过敏", "严重肝肾功能不全"],
     "side_effects": ["皮疹", "骨髓抑制", "高钾血症"], "metabolism": "CYP2C9/NAT2"},
    {"id": "fosfomycin", "name": "磷霉素", "category": "磷霉素类", "generic_name": "磷霉素氨丁三醇",
     "contraindications": ["磷霉素过敏"],
     "side_effects": ["腹泻", "头痛", "恶心"], "metabolism": "不代谢"},

    # ==================== 抗真菌药 ====================
    {"id": "fluconazole", "name": "氟康唑", "category": "抗真菌药", "generic_name": "氟康唑",
     "contraindications": ["QT延长", "严重肝功能不全"],
     "side_effects": ["肝毒性", "QT延长", "恶心"], "metabolism": "CYP2C9/CYP3A4"},
    {"id": "itraconazole", "name": "伊曲康唑", "category": "抗真菌药", "generic_name": "伊曲康唑",
     "contraindications": ["心衰"],
     "side_effects": ["肝毒性", "心衰加重", "低钾血症"], "metabolism": "CYP3A4"},
    {"id": "voriconazole", "name": "伏立康唑", "category": "抗真菌药", "generic_name": "伏立康唑",
     "contraindications": ["QT延长", "严重肝功能不全"],
     "side_effects": ["视觉障碍", "肝毒性", "光敏反应"], "metabolism": "CYP2C19/CYP3A4"},
    {"id": "posaconazole", "name": "泊沙康唑", "category": "抗真菌药", "generic_name": "泊沙康唑",
     "contraindications": ["QT延长"],
     "side_effects": ["恶心", "腹泻", "QT延长"], "metabolism": "UGT"},
    {"id": "amphotericin_b", "name": "两性霉素B", "category": "抗真菌药", "generic_name": "两性霉素B",
     "contraindications": ["严重肾功能不全"],
     "side_effects": ["肾毒性", "输液反应", "低钾血症"], "metabolism": "不明"},
    {"id": "caspofungin", "name": "卡泊芬净", "category": "抗真菌药", "generic_name": "醋酸卡泊芬净",
     "contraindications": ["卡泊芬净过敏"],
     "side_effects": ["发热", "静脉炎", "肝功能异常"], "metabolism": "肝脏水解"},
    {"id": "griseofulvin", "name": "灰黄霉素", "category": "抗真菌药", "generic_name": "灰黄霉素",
     "contraindications": ["肝功能不全", "卟啉症", "孕妇"],
     "side_effects": ["头痛", "光敏反应", "肝毒性"], "metabolism": "CYP1A2/CYP3A4"},

    # ==================== 抗病毒药 ====================
    {"id": "oseltamivir", "name": "奥司他韦", "category": "抗病毒药", "generic_name": "磷酸奥司他韦",
     "contraindications": ["奥司他韦过敏"],
     "side_effects": ["恶心", "呕吐", "神经精神症状"], "metabolism": "酯酶水解"},
    {"id": "acyclovir", "name": "阿昔洛韦", "category": "抗病毒药", "generic_name": "阿昔洛韦",
     "contraindications": ["阿昔洛韦过敏"],
     "side_effects": ["肾毒性", "神经毒性", "结晶尿"], "metabolism": "少量肝脏代谢"},
    {"id": "valacyclovir", "name": "伐昔洛韦", "category": "抗病毒药", "generic_name": "盐酸伐昔洛韦",
     "contraindications": ["伐昔洛韦过敏"],
     "side_effects": ["头痛", "恶心"], "metabolism": "水解为阿昔洛韦"},
    {"id": "ganciclovir", "name": "更昔洛韦", "category": "抗病毒药", "generic_name": "更昔洛韦",
     "contraindications": ["中性粒细胞<500", "血小板<25000"],
     "side_effects": ["骨髓抑制", "肾毒性", "神经毒性"], "metabolism": "肾脏排泄"},
    {"id": "tenofovir", "name": "替诺福韦", "category": "抗病毒药",
     "generic_name": "富马酸替诺福韦二吡呋酯",
     "contraindications": ["替诺福韦过敏"],
     "side_effects": ["肾毒性", "骨密度降低", "乳酸酸中毒"], "metabolism": "肾脏排泄"},
    {"id": "entecavir", "name": "恩替卡韦", "category": "抗病毒药", "generic_name": "恩替卡韦",
     "contraindications": ["恩替卡韦过敏"],
     "side_effects": ["头痛", "疲劳", "乳酸酸中毒(罕见)"], "metabolism": "部分CYP代谢"},
    {"id": "sofosbuvir", "name": "索磷布韦", "category": "抗病毒药", "generic_name": "索磷布韦",
     "contraindications": ["索磷布韦过敏"],
     "side_effects": ["疲劳", "头痛", "恶心"], "metabolism": "前药"},

    # ==================== 精神科药物 ====================
    {"id": "olanzapine", "name": "奥氮平", "category": "抗精神病药", "generic_name": "奥氮平",
     "contraindications": ["闭角型青光眼"],
     "side_effects": ["代谢综合征", "嗜睡", "体重增加"], "metabolism": "CYP1A2/CYP2D6"},
    {"id": "quetiapine", "name": "喹硫平", "category": "抗精神病药", "generic_name": "富马酸喹硫平",
     "contraindications": ["QT延长"],
     "side_effects": ["嗜睡", "体重增加", "QT延长"], "metabolism": "CYP3A4"},
    {"id": "aripiprazole", "name": "阿立哌唑", "category": "抗精神病药", "generic_name": "阿立哌唑",
     "contraindications": ["阿立哌唑过敏"],
     "side_effects": ["静坐不能", "失眠", "恶心"], "metabolism": "CYP2D6/CYP3A4"},
    {"id": "risperidone", "name": "利培酮", "category": "抗精神病药", "generic_name": "利培酮",
     "contraindications": ["利培酮过敏"],
     "side_effects": ["锥体外系反应", "高催乳素血症"], "metabolism": "CYP2D6/CYP3A4"},
    {"id": "paliperidone", "name": "帕利哌酮", "category": "抗精神病药", "generic_name": "帕利哌酮",
     "contraindications": ["帕利哌酮过敏"],
     "side_effects": ["锥体外系反应", "高催乳素血症", "QT延长"], "metabolism": "CYP2D6(少量)"},
    {"id": "haloperidol", "name": "氟哌啶醇", "category": "抗精神病药", "generic_name": "氟哌啶醇",
     "contraindications": ["帕金森病", "昏迷", "QT延长"],
     "side_effects": ["锥体外系反应", "QT延长", "恶性综合征"], "metabolism": "CYP3A4/CYP2D6"},
    {"id": "clozapine", "name": "氯氮平", "category": "抗精神病药", "generic_name": "氯氮平",
     "contraindications": ["粒细胞缺乏史", "癫痫未控制"],
     "side_effects": ["粒细胞缺乏", "代谢综合征", "心肌炎"], "metabolism": "CYP1A2/CYP3A4"},
    {"id": "ziprasidone", "name": "齐拉西酮", "category": "抗精神病药", "generic_name": "盐酸齐拉西酮",
     "contraindications": ["QT延长", "近期心肌梗死"],
     "side_effects": ["QT延长", "嗜睡", "恶心"], "metabolism": "CYP3A4"},
    {"id": "lithium", "name": "锂盐", "category": "情绪稳定剂", "generic_name": "碳酸锂",
     "contraindications": ["严重肾功能不全", "严重脱水"],
     "side_effects": ["锂中毒", "甲状腺功能减退", "肾源性尿崩症"], "metabolism": "肾脏排泄"},
    {"id": "valproic_acid", "name": "丙戊酸", "category": "抗癫痫药", "generic_name": "丙戊酸钠",
     "contraindications": ["肝病", "尿素循环障碍", "孕妇"],
     "side_effects": ["肝毒性", "胰腺炎", "致畸", "血小板减少"], "metabolism": "CYP2C9/葡萄糖醛酸结合"},
    {"id": "carbamazepine", "name": "卡马西平", "category": "抗癫痫药", "generic_name": "卡马西平",
     "contraindications": ["骨髓抑制", "房室传导阻滞", "卟啉症"],
     "side_effects": ["粒细胞减少", "皮疹(SJS风险)", "低钠血症"], "metabolism": "CYP3A4(自诱导)"},
    {"id": "lamotrigine", "name": "拉莫三嗪", "category": "抗癫痫药", "generic_name": "拉莫三嗪",
     "contraindications": ["拉莫三嗪过敏"],
     "side_effects": ["SJS/TEN", "头痛", "头晕"], "metabolism": "葡萄糖醛酸结合"},
    {"id": "levetiracetam", "name": "左乙拉西坦", "category": "抗癫痫药", "generic_name": "左乙拉西坦",
     "contraindications": ["左乙拉西坦过敏"],
     "side_effects": ["嗜睡", "头晕", "行为异常"], "metabolism": "酯酶水解"},
    {"id": "topiramate", "name": "托吡酯", "category": "抗癫痫药", "generic_name": "托吡酯",
     "contraindications": ["肾结石", "代谢性酸中毒"],
     "side_effects": ["认知障碍", "肾结石", "体重减轻"], "metabolism": "部分CYP代谢"},
    {"id": "pregabalin", "name": "普瑞巴林", "category": "神经痛药物", "generic_name": "普瑞巴林",
     "contraindications": ["普瑞巴林过敏"],
     "side_effects": ["头晕", "嗜睡", "体重增加"], "metabolism": "不代谢"},
    {"id": "gabapentin", "name": "加巴喷丁", "category": "神经痛药物", "generic_name": "加巴喷丁",
     "contraindications": ["加巴喷丁过敏"],
     "side_effects": ["嗜睡", "头晕", "外周水肿"], "metabolism": "不代谢"},
    {"id": "duloxetine", "name": "度洛西汀", "category": "SNRI", "generic_name": "盐酸度洛西汀",
     "contraindications": ["MAO抑制剂使用中", "严重肝功能不全"],
     "side_effects": ["恶心", "口干", "血压升高"], "metabolism": "CYP1A2/CYP2D6"},
    {"id": "venlafaxine", "name": "文拉法辛", "category": "SNRI", "generic_name": "盐酸文拉法辛",
     "contraindications": ["MAO抑制剂使用中"],
     "side_effects": ["恶心", "头晕", "高血压"], "metabolism": "CYP2D6/CYP3A4"},
    {"id": "mirtazapine", "name": "米氮平", "category": "NaSSA", "generic_name": "米氮平",
     "contraindications": ["MAO抑制剂使用中"],
     "side_effects": ["嗜睡", "体重增加", "口干"], "metabolism": "CYP1A2/CYP2D6/CYP3A4"},
    {"id": "trazodone", "name": "曲唑酮", "category": "SARI", "generic_name": "盐酸曲唑酮",
     "contraindications": ["MAO抑制剂使用中"],
     "side_effects": ["嗜睡", "体位性低血压"], "metabolism": "CYP3A4"},
    {"id": "methylphenidate", "name": "哌甲酯", "category": "中枢兴奋药", "generic_name": "盐酸哌甲酯",
     "contraindications": ["焦虑", "青光眼", "抽动症", "MAO抑制剂使用中"],
     "side_effects": ["失眠", "食欲减退", "心动过速"], "metabolism": "CES1"},
    {"id": "atomoxetine", "name": "托莫西汀", "category": "NRI", "generic_name": "盐酸托莫西汀",
     "contraindications": ["MAO抑制剂使用中", "嗜铬细胞瘤"],
     "side_effects": ["恶心", "食欲减退", "肝毒性(罕见)"], "metabolism": "CYP2D6"},
    {"id": "buspirone", "name": "丁螺环酮", "category": "抗焦虑药", "generic_name": "盐酸丁螺环酮",
     "contraindications": ["MAO抑制剂使用中"],
     "side_effects": ["头晕", "恶心", "头痛"], "metabolism": "CYP3A4"},
    {"id": "hydroxyzine", "name": "羟嗪", "category": "抗焦虑药", "generic_name": "盐酸羟嗪",
     "contraindications": ["QT延长", "孕妇早期"],
     "side_effects": ["嗜睡", "口干", "QT延长"], "metabolism": "CYP3A4/CYP2D6"},

    # ==================== 内分泌 ====================
    {"id": "metformin", "name": "二甲双胍", "category": "双胍类降糖药", "generic_name": "盐酸二甲双胍",
     "contraindications": ["eGFR<30", "代谢性酸中毒", "急性心衰"],
     "side_effects": ["乳酸酸中毒", "胃肠道反应", "维生素B12缺乏"], "metabolism": "不代谢"},
    {"id": "glimepiride", "name": "格列美脲", "category": "磺脲类降糖药", "generic_name": "格列美脲",
     "contraindications": ["1型糖尿病", "酮症酸中毒", "严重肝肾功能不全"],
     "side_effects": ["低血糖", "体重增加"], "metabolism": "CYP2C9"},
    {"id": "gliclazide", "name": "格列齐特", "category": "磺脲类降糖药", "generic_name": "格列齐特",
     "contraindications": ["1型糖尿病", "酮症酸中毒"],
     "side_effects": ["低血糖", "体重增加"], "metabolism": "CYP2C9"},
    {"id": "repaglinide", "name": "瑞格列奈", "category": "格列奈类", "generic_name": "瑞格列奈",
     "contraindications": ["1型糖尿病", "酮症酸中毒"],
     "side_effects": ["低血糖", "体重增加"], "metabolism": "CYP2C8/CYP3A4"},
    {"id": "pioglitazone", "name": "吡格列酮", "category": "噻唑烷二酮类", "generic_name": "盐酸吡格列酮",
     "contraindications": ["心衰", "活动性肝病"],
     "side_effects": ["液体潴留", "体重增加", "骨折风险"], "metabolism": "CYP2C8"},
    {"id": "acarbose", "name": "阿卡波糖", "category": "α-糖苷酶抑制剂", "generic_name": "阿卡波糖",
     "contraindications": ["炎症性肠病", "肠梗阻", "肝硬化"],
     "side_effects": ["腹胀", "腹泻"], "metabolism": "肠道菌群分解"},
    {"id": "liraglutide", "name": "利拉鲁肽", "category": "GLP-1受体激动剂", "generic_name": "利拉鲁肽",
     "contraindications": ["甲状腺髓样癌史", "MEN2"],
     "side_effects": ["恶心", "呕吐", "胰腺炎风险"], "metabolism": "蛋白水解"},
    {"id": "semaglutide", "name": "司美格鲁肽", "category": "GLP-1受体激动剂", "generic_name": "司美格鲁肽",
     "contraindications": ["甲状腺髓样癌史", "MEN2"],
     "side_effects": ["恶心", "呕吐", "腹泻"], "metabolism": "蛋白水解"},
    {"id": "empagliflozin", "name": "恩格列净", "category": "SGLT2抑制剂", "generic_name": "恩格列净",
     "contraindications": ["严重肾功能不全", "透析"],
     "side_effects": ["泌尿生殖感染", "酮症酸中毒", "脱水"], "metabolism": "UGT1A9"},
    {"id": "dapagliflozin", "name": "达格列净", "category": "SGLT2抑制剂", "generic_name": "达格列净",
     "contraindications": ["透析"],
     "side_effects": ["泌尿生殖感染", "酮症酸中毒"], "metabolism": "UGT1A9"},
    {"id": "canagliflozin", "name": "卡格列净", "category": "SGLT2抑制剂", "generic_name": "卡格列净",
     "contraindications": ["透析"],
     "side_effects": ["泌尿生殖感染", "酮症酸中毒", "截肢风险"], "metabolism": "UGT1A9"},
    {"id": "linagliptin", "name": "利格列汀", "category": "DPP-4抑制剂", "generic_name": "利格列汀",
     "contraindications": ["利格列汀过敏"],
     "side_effects": ["鼻咽炎", "头痛"], "metabolism": "CYP3A4(少量)"},
    {"id": "saxagliptin", "name": "沙格列汀", "category": "DPP-4抑制剂", "generic_name": "沙格列汀",
     "contraindications": ["心衰"],
     "side_effects": ["上呼吸道感染", "头痛"], "metabolism": "CYP3A4"},
    {"id": "levothyroxine", "name": "左甲状腺素", "category": "甲状腺激素", "generic_name": "左甲状腺素钠",
     "contraindications": ["未治疗的肾上腺功能不全", "急性心肌梗死"],
     "side_effects": ["甲亢症状", "心悸"], "metabolism": "肝脏代谢"},
    {"id": "methimazole", "name": "甲巯咪唑", "category": "抗甲状腺药", "generic_name": "甲巯咪唑",
     "contraindications": ["粒细胞缺乏"],
     "side_effects": ["粒细胞缺乏", "肝毒性", "皮疹"], "metabolism": "甲状腺内浓缩"},
    {"id": "propylthiouracil", "name": "丙硫氧嘧啶", "category": "抗甲状腺药", "generic_name": "丙硫氧嘧啶",
     "contraindications": ["严重肝功能不全"],
     "side_effects": ["肝毒性", "粒细胞缺乏"], "metabolism": "肝脏代谢"},
    {"id": "insulin_glargine", "name": "甘精胰岛素", "category": "胰岛素", "generic_name": "甘精胰岛素",
     "contraindications": ["低血糖"],
     "side_effects": ["低血糖", "体重增加"], "metabolism": "蛋白水解"},
    {"id": "insulin_aspart", "name": "门冬胰岛素", "category": "胰岛素", "generic_name": "门冬胰岛素",
     "contraindications": ["低血糖"],
     "side_effects": ["低血糖", "体重增加"], "metabolism": "蛋白水解"},

    # ==================== 呼吸系统 ====================
    {"id": "salbutamol", "name": "沙丁胺醇", "category": "β2受体激动剂", "generic_name": "硫酸沙丁胺醇",
     "contraindications": ["对本品过敏"],
     "side_effects": ["心动过速", "震颤", "低钾血症"], "metabolism": "SULT1A3"},
    {"id": "formoterol", "name": "福莫特罗", "category": "β2受体激动剂", "generic_name": "富马酸福莫特罗",
     "contraindications": ["对本品过敏"],
     "side_effects": ["心动过速", "震颤"], "metabolism": "CYP2D6/CYP2C19"},
    {"id": "salmeterol", "name": "沙美特罗", "category": "β2受体激动剂",
     "generic_name": "昔萘酸沙美特罗",
     "contraindications": ["对本品过敏"],
     "side_effects": ["头痛", "震颤", "心悸"], "metabolism": "CYP3A4"},
    {"id": "tiotropium", "name": "噻托溴铵", "category": "抗胆碱药", "generic_name": "噻托溴铵",
     "contraindications": ["对阿托品类过敏"],
     "side_effects": ["口干", "尿潴留"], "metabolism": "CYP2D6/CYP3A4"},
    {"id": "ipratropium", "name": "异丙托溴铵", "category": "抗胆碱药", "generic_name": "异丙托溴铵",
     "contraindications": ["对阿托品类过敏"],
     "side_effects": ["口干", "尿潴留"], "metabolism": "酯酶水解"},
    {"id": "budesonide", "name": "布地奈德", "category": "吸入性糖皮质激素", "generic_name": "布地奈德",
     "contraindications": ["哮喘急性发作(单药)"],
     "side_effects": ["口腔念珠菌感染", "声音嘶哑"], "metabolism": "CYP3A4"},
    {"id": "fluticasone", "name": "氟替卡松", "category": "吸入性糖皮质激素",
     "generic_name": "丙酸氟替卡松",
     "contraindications": ["哮喘急性发作(单药)"],
     "side_effects": ["口腔念珠菌感染", "声音嘶哑"], "metabolism": "CYP3A4"},
    {"id": "montelukast", "name": "孟鲁司特", "category": "白三烯受体拮抗剂",
     "generic_name": "孟鲁司特钠",
     "contraindications": ["对本品过敏"],
     "side_effects": ["头痛", "神经精神事件"], "metabolism": "CYP2C8/CYP3A4"},
    {"id": "theophylline", "name": "茶碱", "category": "黄嘌呤类", "generic_name": "茶碱",
     "contraindications": ["活动性消化道溃疡", "癫痫"],
     "side_effects": ["恶心", "心动过速", "癫痫发作(中毒)"], "metabolism": "CYP1A2"},
    {"id": "ambroxol", "name": "氨溴索", "category": "祛痰药", "generic_name": "盐酸氨溴索",
     "contraindications": ["严重肝肾功能不全"],
     "side_effects": ["恶心", "过敏反应(罕见)"], "metabolism": "肝脏代谢"},
    {"id": "acetylcysteine", "name": "乙酰半胱氨酸", "category": "祛痰药",
     "generic_name": "乙酰半胱氨酸",
     "contraindications": ["哮喘(雾化)"],
     "side_effects": ["恶心", "呕吐"], "metabolism": "肝脏代谢"},
    {"id": "dextromethorphan", "name": "右美沙芬", "category": "镇咳药",
     "generic_name": "氢溴酸右美沙芬",
     "contraindications": ["MAO抑制剂使用中"],
     "side_effects": ["嗜睡", "头晕", "5-HT综合征(合用SSRI)"], "metabolism": "CYP2D6"},
    {"id": "codeine", "name": "可待因", "category": "镇咳药", "generic_name": "磷酸可待因",
     "contraindications": ["儿童(<12岁)", "CYP2D6超快代谢者"],
     "side_effects": ["便秘", "呼吸抑制", "成瘾"], "metabolism": "CYP2D6"},
    {"id": "omalizumab", "name": "奥马珠单抗", "category": "抗IgE单抗", "generic_name": "奥马珠单抗",
     "contraindications": ["对本品过敏"],
     "side_effects": ["注射部位反应", "过敏反应"], "metabolism": "网状内皮系统"},

    # ==================== 消化系统 ====================
    {"id": "omeprazole", "name": "奥美拉唑", "category": "PPI", "generic_name": "奥美拉唑",
     "contraindications": ["奥美拉唑过敏"],
     "side_effects": ["头痛", "腹泻", "骨质疏松(长期)"], "metabolism": "CYP2C19/CYP3A4"},
    {"id": "esomeprazole", "name": "埃索美拉唑", "category": "PPI", "generic_name": "埃索美拉唑镁",
     "contraindications": ["埃索美拉唑过敏"],
     "side_effects": ["头痛", "腹泻"], "metabolism": "CYP2C19/CYP3A4"},
    {"id": "pantoprazole", "name": "泮托拉唑", "category": "PPI", "generic_name": "泮托拉唑钠",
     "contraindications": ["泮托拉唑过敏"],
     "side_effects": ["头痛", "腹泻"], "metabolism": "CYP2C19"},
    {"id": "rabeprazole", "name": "雷贝拉唑", "category": "PPI", "generic_name": "雷贝拉唑钠",
     "contraindications": ["雷贝拉唑过敏"],
     "side_effects": ["头痛", "腹泻"], "metabolism": "非酶代谢为主"},
    {"id": "famotidine", "name": "法莫替丁", "category": "H2受体拮抗剂", "generic_name": "法莫替丁",
     "contraindications": ["法莫替丁过敏"],
     "side_effects": ["头痛", "头晕", "便秘"], "metabolism": "少量肝脏代谢"},
    {"id": "cimetidine", "name": "西咪替丁", "category": "H2受体拮抗剂", "generic_name": "西咪替丁",
     "contraindications": ["西咪替丁过敏"],
     "side_effects": ["抗雄激素作用", "CYP抑制"], "metabolism": "CYP1A2/CYP2C9/CYP3A4"},
    {"id": "mosapride", "name": "莫沙必利", "category": "促胃动力药", "generic_name": "枸橼酸莫沙必利",
     "contraindications": ["胃肠道出血", "肠梗阻"],
     "side_effects": ["腹泻", "腹痛"], "metabolism": "CYP3A4"},
    {"id": "domperidone", "name": "多潘立酮", "category": "促胃动力药", "generic_name": "多潘立酮",
     "contraindications": ["垂体瘤", "QT延长", "胃肠道出血"],
     "side_effects": ["QT延长", "溢乳"], "metabolism": "CYP3A4"},
    {"id": "ondansetron", "name": "昂丹司琼", "category": "止吐药", "generic_name": "盐酸昂丹司琼",
     "contraindications": ["QT延长"],
     "side_effects": ["QT延长", "头痛", "便秘"], "metabolism": "CYP1A2/CYP2D6/CYP3A4"},
    {"id": "granisetron", "name": "格拉司琼", "category": "止吐药", "generic_name": "盐酸格拉司琼",
     "contraindications": ["格拉司琼过敏"],
     "side_effects": ["头痛", "便秘"], "metabolism": "CYP3A4"},
    {"id": "aprepitant", "name": "阿瑞匹坦", "category": "NK-1受体拮抗剂", "generic_name": "阿瑞匹坦",
     "contraindications": ["CYP3A4强底物合用"],
     "side_effects": ["疲劳", "便秘"], "metabolism": "CYP3A4"},
    {"id": "loperamide", "name": "洛哌丁胺", "category": "止泻药", "generic_name": "盐酸洛哌丁胺",
     "contraindications": ["溃疡性结肠炎急性期", "艰难梭菌感染"],
     "side_effects": ["便秘", "腹胀"], "metabolism": "CYP3A4/CYP2C8"},
    {"id": "lactulose", "name": "乳果糖", "category": "渗透性泻剂", "generic_name": "乳果糖",
     "contraindications": ["半乳糖血症", "肠梗阻"],
     "side_effects": ["腹胀", "腹泻"], "metabolism": "肠道菌群代谢"},
    {"id": "ursodeoxycholic_acid", "name": "熊去氧胆酸", "category": "利胆药",
     "generic_name": "熊去氧胆酸",
     "contraindications": ["胆道完全梗阻"],
     "side_effects": ["腹泻", "瘙痒"], "metabolism": "肝脏代谢"},
    {"id": "sucralfate", "name": "硫糖铝", "category": "胃黏膜保护剂", "generic_name": "硫糖铝",
     "contraindications": ["肾功能不全(铝蓄积)"],
     "side_effects": ["便秘", "铝蓄积"], "metabolism": "不吸收"},
    {"id": "misoprostol", "name": "米索前列醇", "category": "前列腺素类似物",
     "generic_name": "米索前列醇",
     "contraindications": ["孕妇(致流产)"],
     "side_effects": ["腹泻", "腹痛", "子宫收缩"], "metabolism": "脂肪酸氧化"},

    # ==================== 镇痛药 ====================
    {"id": "celecoxib", "name": "塞来昔布", "category": "COX-2抑制剂", "generic_name": "塞来昔布",
     "contraindications": ["磺胺过敏", "活动性消化道出血", "CABG围术期"],
     "side_effects": ["心血管事件风险", "消化道反应"], "metabolism": "CYP2C9"},
    {"id": "ketorolac", "name": "酮咯酸", "category": "NSAIDs", "generic_name": "酮咯酸氨丁三醇",
     "contraindications": ["活动性消化道出血", "肾功能不全"],
     "side_effects": ["消化道出血", "肾损害"], "metabolism": "CYP2C9"},
    {"id": "meloxicam", "name": "美洛昔康", "category": "NSAIDs", "generic_name": "美洛昔康",
     "contraindications": ["活动性消化道溃疡"],
     "side_effects": ["消化道反应", "肾损害"], "metabolism": "CYP2C9"},
    {"id": "fentanyl", "name": "芬太尼", "category": "阿片类镇痛药", "generic_name": "枸橼酸芬太尼",
     "contraindications": ["呼吸抑制", "急性腹痛未诊断"],
     "side_effects": ["呼吸抑制", "便秘", "成瘾"], "metabolism": "CYP3A4"},
    {"id": "oxycodone", "name": "羟考酮", "category": "阿片类镇痛药", "generic_name": "盐酸羟考酮",
     "contraindications": ["呼吸抑制"],
     "side_effects": ["呼吸抑制", "便秘", "成瘾"], "metabolism": "CYP3A4/CYP2D6"},
    {"id": "buprenorphine", "name": "丁丙诺啡", "category": "阿片类镇痛药",
     "generic_name": "盐酸丁丙诺啡",
     "contraindications": ["呼吸抑制"],
     "side_effects": ["呼吸抑制(有天花板)", "恶心"], "metabolism": "CYP3A4"},
    {"id": "tapentadol", "name": "他喷他多", "category": "阿片类镇痛药",
     "generic_name": "盐酸他喷他多",
     "contraindications": ["MAO抑制剂使用中", "呼吸抑制"],
     "side_effects": ["恶心", "头晕", "5-HT综合征"], "metabolism": "UGT"},
    {"id": "allopurinol", "name": "别嘌醇", "category": "抗痛风药", "generic_name": "别嘌醇",
     "contraindications": ["严重过敏反应史"],
     "side_effects": ["SJS/TEN(HLA-B*5801)", "肝毒性", "骨髓抑制"], "metabolism": "黄嘌呤氧化酶"},
    {"id": "febuxostat", "name": "非布司他", "category": "抗痛风药", "generic_name": "非布司他",
     "contraindications": ["心血管疾病(增加死亡率)"],
     "side_effects": ["肝功能异常", "心血管事件风险"], "metabolism": "CYP1A2/UGT"},

    # ==================== 免疫抑制剂 ====================
    {"id": "tacrolimus", "name": "他克莫司", "category": "免疫抑制剂", "generic_name": "他克莫司",
     "contraindications": ["对他克莫司过敏"],
     "side_effects": ["肾毒性", "高血糖", "神经毒性"], "metabolism": "CYP3A4/CYP3A5"},
    {"id": "sirolimus", "name": "西罗莫司", "category": "免疫抑制剂", "generic_name": "西罗莫司",
     "contraindications": ["对西罗莫司过敏"],
     "side_effects": ["高脂血症", "血小板减少", "伤口愈合延迟"], "metabolism": "CYP3A4"},
    {"id": "everolimus", "name": "依维莫司", "category": "免疫抑制剂/抗肿瘤",
     "generic_name": "依维莫司",
     "contraindications": ["对依维莫司过敏"],
     "side_effects": ["口腔炎", "肺炎", "高血糖"], "metabolism": "CYP3A4"},
    {"id": "azathioprine", "name": "硫唑嘌呤", "category": "免疫抑制剂", "generic_name": "硫唑嘌呤",
     "contraindications": ["TPMT缺乏"],
     "side_effects": ["骨髓抑制", "肝毒性", "胰腺炎"], "metabolism": "TPMT/XO"},
    {"id": "mycophenolate", "name": "吗替麦考酚酯", "category": "免疫抑制剂",
     "generic_name": "吗替麦考酚酯",
     "contraindications": ["孕妇"],
     "side_effects": ["骨髓抑制", "感染", "胃肠道反应"], "metabolism": "UGT"},
    {"id": "leflunomide", "name": "来氟米特", "category": "免疫抑制剂", "generic_name": "来氟米特",
     "contraindications": ["孕妇(致畸)", "严重肝功能不全"],
     "side_effects": ["肝毒性", "腹泻", "脱发"], "metabolism": "CYP1A2/CYP2C19"},

    # ==================== 抗肿瘤药 ====================
    {"id": "cyclophosphamide", "name": "环磷酰胺", "category": "抗肿瘤药", "generic_name": "环磷酰胺",
     "contraindications": ["严重骨髓抑制"],
     "side_effects": ["骨髓抑制", "出血性膀胱炎", "不孕"], "metabolism": "CYP2B6/CYP3A4"},
    {"id": "doxorubicin", "name": "多柔比星", "category": "抗肿瘤药", "generic_name": "盐酸多柔比星",
     "contraindications": ["严重骨髓抑制", "心功能不全"],
     "side_effects": ["心脏毒性", "骨髓抑制", "脱发"], "metabolism": "CYP3A4/CYP2D6"},
    {"id": "paclitaxel", "name": "紫杉醇", "category": "抗肿瘤药", "generic_name": "紫杉醇",
     "contraindications": ["中性粒细胞<1500"],
     "side_effects": ["骨髓抑制", "过敏反应", "周围神经病变"], "metabolism": "CYP2C8/CYP3A4"},
    {"id": "cisplatin", "name": "顺铂", "category": "抗肿瘤药", "generic_name": "顺铂",
     "contraindications": ["肾功能不全", "听力损害"],
     "side_effects": ["肾毒性", "耳毒性", "神经毒性"], "metabolism": "非酶代谢"},
    {"id": "carboplatin", "name": "卡铂", "category": "抗肿瘤药", "generic_name": "卡铂",
     "contraindications": ["严重骨髓抑制"],
     "side_effects": ["骨髓抑制(血小板为主)"], "metabolism": "肾脏排泄"},
    {"id": "fluorouracil", "name": "氟尿嘧啶", "category": "抗肿瘤药", "generic_name": "氟尿嘧啶",
     "contraindications": ["严重骨髓抑制", "DPD缺乏"],
     "side_effects": ["骨髓抑制", "口腔炎", "手足综合征"], "metabolism": "DPD"},
    {"id": "capecitabine", "name": "卡培他滨", "category": "抗肿瘤药", "generic_name": "卡培他滨",
     "contraindications": ["DPD缺乏"],
     "side_effects": ["手足综合征", "腹泻", "骨髓抑制"], "metabolism": "三步酶活化"},
    {"id": "oxaliplatin", "name": "奥沙利铂", "category": "抗肿瘤药", "generic_name": "奥沙利铂",
     "contraindications": ["严重肾功能不全"],
     "side_effects": ["周围神经病变", "骨髓抑制"], "metabolism": "非酶水解"},
    {"id": "irinotecan", "name": "伊立替康", "category": "抗肿瘤药", "generic_name": "盐酸伊立替康",
     "contraindications": ["严重骨髓抑制"],
     "side_effects": ["迟发性腹泻", "骨髓抑制"], "metabolism": "CYP3A4/UGT1A1"},
    {"id": "pemetrexed", "name": "培美曲塞", "category": "抗肿瘤药", "generic_name": "培美曲塞二钠",
     "contraindications": ["严重肾功能不全"],
     "side_effects": ["骨髓抑制", "皮疹"], "metabolism": "肾脏排泄"},
    {"id": "gemcitabine", "name": "吉西他滨", "category": "抗肿瘤药", "generic_name": "盐酸吉西他滨",
     "contraindications": ["严重骨髓抑制"],
     "side_effects": ["骨髓抑制", "肝毒性", "肺毒性"], "metabolism": "胞苷脱氨酶"},
    {"id": "vinorelbine", "name": "长春瑞滨", "category": "抗肿瘤药", "generic_name": "酒石酸长春瑞滨",
     "contraindications": ["严重骨髓抑制"],
     "side_effects": ["骨髓抑制", "神经毒性"], "metabolism": "CYP3A4"},
    {"id": "docetaxel", "name": "多西他赛", "category": "抗肿瘤药", "generic_name": "多西他赛",
     "contraindications": ["中性粒细胞<1500"],
     "side_effects": ["骨髓抑制", "过敏反应"], "metabolism": "CYP3A4"},
    {"id": "erlotinib", "name": "厄洛替尼", "category": "抗肿瘤药", "generic_name": "盐酸厄洛替尼",
     "contraindications": ["严重肝功能不全"],
     "side_effects": ["皮疹", "腹泻", "间质性肺炎"], "metabolism": "CYP1A2/CYP3A4"},
    {"id": "gefitinib", "name": "吉非替尼", "category": "抗肿瘤药", "generic_name": "吉非替尼",
     "contraindications": ["严重肝功能不全"],
     "side_effects": ["皮疹", "腹泻"], "metabolism": "CYP3A4/CYP2D6"},
    {"id": "imatinib", "name": "伊马替尼", "category": "抗肿瘤药", "generic_name": "甲磺酸伊马替尼",
     "contraindications": ["严重肝功能不全"],
     "side_effects": ["水肿", "恶心", "骨髓抑制"], "metabolism": "CYP3A4"},
    {"id": "sorafenib", "name": "索拉非尼", "category": "抗肿瘤药", "generic_name": "甲苯磺酸索拉非尼",
     "contraindications": ["QT延长"],
     "side_effects": ["手足综合征", "腹泻", "高血压"], "metabolism": "CYP3A4"},
    {"id": "lenvatinib", "name": "仑伐替尼", "category": "抗肿瘤药", "generic_name": "甲磺酸仑伐替尼",
     "contraindications": ["严重肝功能不全"],
     "side_effects": ["高血压", "腹泻", "蛋白尿"], "metabolism": "CYP3A4"},

    # ==================== 妇科 ====================
    {"id": "tamoxifen", "name": "他莫昔芬", "category": "抗雌激素药", "generic_name": "枸橼酸他莫昔芬",
     "contraindications": ["孕妇", "血栓栓塞病史"],
     "side_effects": ["子宫内膜癌风险", "血栓栓塞"], "metabolism": "CYP2D6"},
    {"id": "anastrozole", "name": "阿那曲唑", "category": "芳香化酶抑制剂",
     "generic_name": "阿那曲唑",
     "contraindications": ["孕妇", "绝经前妇女"],
     "side_effects": ["骨质疏松", "关节痛"], "metabolism": "CYP3A4/UGT"},
    {"id": "letrozole", "name": "来曲唑", "category": "芳香化酶抑制剂", "generic_name": "来曲唑",
     "contraindications": ["孕妇", "绝经前妇女"],
     "side_effects": ["骨质疏松", "关节痛"], "metabolism": "CYP2A6/CYP3A4"},

    # ==================== 泌尿系统 ====================
    {"id": "tamsulosin", "name": "坦索罗辛", "category": "α受体阻滞剂",
     "generic_name": "盐酸坦索罗辛",
     "contraindications": ["体位性低血压"],
     "side_effects": ["头晕", "射精异常"], "metabolism": "CYP3A4/CYP2D6"},
    {"id": "finasteride", "name": "非那雄胺", "category": "5α还原酶抑制剂",
     "generic_name": "非那雄胺",
     "contraindications": ["孕妇(致畸)", "儿童"],
     "side_effects": ["性功能障碍", "乳房发育"], "metabolism": "CYP3A4"},
    {"id": "sildenafil", "name": "西地那非", "category": "PDE5抑制剂",
     "generic_name": "枸橼酸西地那非",
     "contraindications": ["硝酸酯类使用中", "严重肝功能不全"],
     "side_effects": ["头痛", "面部潮红", "视觉异常"], "metabolism": "CYP3A4/CYP2C9"},
    {"id": "tadalafil", "name": "他达拉非", "category": "PDE5抑制剂", "generic_name": "他达拉非",
     "contraindications": ["硝酸酯类使用中"],
     "side_effects": ["头痛", "消化不良", "背痛"], "metabolism": "CYP1A2/CYP3A4"},

    # ==================== 眼科 ====================
    {"id": "timolol_eye", "name": "噻吗洛尔(眼)", "category": "β受体阻滞剂(眼科)",
     "generic_name": "马来酸噻吗洛尔",
     "contraindications": ["哮喘", "窦性心动过缓", "心衰"],
     "side_effects": ["心动过缓", "支气管痉挛"], "metabolism": "全身吸收"},
    {"id": "latanoprost", "name": "拉坦前列素", "category": "前列腺素类似物(眼科)",
     "generic_name": "拉坦前列素",
     "contraindications": ["对本品过敏"],
     "side_effects": ["虹膜色素加深", "睫毛生长"], "metabolism": "酯酶水解"},
    {"id": "brimonidine", "name": "溴莫尼定", "category": "α2受体激动剂(眼科)",
     "generic_name": "酒石酸溴莫尼定",
     "contraindications": ["MAO抑制剂使用中", "新生儿"],
     "side_effects": ["口干", "嗜睡"], "metabolism": "肝脏代谢"},

    # ==================== 皮肤科 ====================
    {"id": "tretinoin", "name": "维A酸", "category": "维甲酸类", "generic_name": "维A酸",
     "contraindications": ["孕妇", "哺乳期"],
     "side_effects": ["致畸", "皮肤刺激"], "metabolism": "CYP2C8/CYP2C9"},
    {"id": "isotretinoin", "name": "异维A酸", "category": "维甲酸类", "generic_name": "异维A酸",
     "contraindications": ["孕妇(极高致畸风险)"],
     "side_effects": ["致畸", "唇炎", "肝毒性"], "metabolism": "CYP2C8/CYP2B6"},

    # ==================== 骨科 ====================
    {"id": "alendronate", "name": "阿仑膦酸钠", "category": "双膦酸盐", "generic_name": "阿仑膦酸钠",
     "contraindications": ["食管狭窄", "低钙血症"],
     "side_effects": ["食管溃疡", "下颌骨坏死"], "metabolism": "不代谢"},
    {"id": "zoledronic_acid", "name": "唑来膦酸", "category": "双膦酸盐",
     "generic_name": "唑来膦酸",
     "contraindications": ["严重肾功能不全"],
     "side_effects": ["发热", "骨坏死", "肾毒性"], "metabolism": "不代谢"},
    {"id": "calcium_carbonate", "name": "碳酸钙", "category": "钙剂", "generic_name": "碳酸钙",
     "contraindications": ["高钙血症"],
     "side_effects": ["便秘", "腹胀"], "metabolism": "不代谢"},
    {"id": "vitamin_d3", "name": "维生素D3", "category": "维生素", "generic_name": "胆钙化醇",
     "contraindications": ["高钙血症"],
     "side_effects": ["高钙血症(过量)"], "metabolism": "CYP2R1/CYP27B1"},

    # ==================== 急救/解毒 ====================
    {"id": "naloxone", "name": "纳洛酮", "category": "阿片拮抗剂", "generic_name": "盐酸纳洛酮",
     "contraindications": ["纳洛酮过敏"],
     "side_effects": ["阿片戒断症状"], "metabolism": "UGT"},
    {"id": "flumazenil", "name": "氟马西尼", "category": "苯二氮卓拮抗剂", "generic_name": "氟马西尼",
     "contraindications": ["三环类抗抑郁药过量"],
     "side_effects": ["癫痫发作", "再镇静"], "metabolism": "CYP3A4"},
    {"id": "tranexamic_acid", "name": "氨甲环酸", "category": "抗纤溶药", "generic_name": "氨甲环酸",
     "contraindications": ["活动性血栓栓塞"],
     "side_effects": ["血栓栓塞", "视力障碍"], "metabolism": "肾脏排泄"},
    {"id": "epinephrine", "name": "肾上腺素", "category": "急救药", "generic_name": "盐酸肾上腺素",
     "contraindications": ["无绝对禁忌(过敏性休克时)"],
     "side_effects": ["心动过速", "高血压", "心律失常"], "metabolism": "COMT/MAO"},

    # ==================== 麻醉 ====================
    {"id": "propofol", "name": "丙泊酚", "category": "全身麻醉药", "generic_name": "丙泊酚",
     "contraindications": ["严重低血压"],
     "side_effects": ["低血压", "呼吸抑制", "注射痛"], "metabolism": "CYP2B6/葡萄糖醛酸化"},
    {"id": "lidocaine_local", "name": "利多卡因(局麻)", "category": "局部麻醉药",
     "generic_name": "盐酸利多卡因",
     "contraindications": ["严重窦房传导阻滞"],
     "side_effects": ["中枢神经毒性", "心脏毒性"], "metabolism": "CYP1A2/CYP3A4"},
    {"id": "bupivacaine", "name": "布比卡因", "category": "局部麻醉药", "generic_name": "盐酸布比卡因",
     "contraindications": ["布比卡因过敏"],
     "side_effects": ["心脏毒性", "中枢神经毒性"], "metabolism": "CYP3A4"},

    # ==================== 电解质/营养 ====================
    {"id": "potassium_chloride", "name": "氯化钾", "category": "电解质补充剂",
     "generic_name": "氯化钾",
     "contraindications": ["高钾血症", "严重肾功能不全"],
     "side_effects": ["高钾血症", "消化道刺激"], "metabolism": "肾脏排泄"},
    {"id": "ferrous_sulfate", "name": "硫酸亚铁", "category": "铁剂", "generic_name": "硫酸亚铁",
     "contraindications": ["血色病"],
     "side_effects": ["便秘", "黑便", "恶心"], "metabolism": "十二指肠吸收"},
    {"id": "folic_acid", "name": "叶酸", "category": "维生素", "generic_name": "叶酸",
     "contraindications": ["恶性贫血(需同时补充B12)"],
     "side_effects": ["过敏反应(罕见)"], "metabolism": "二氢叶酸还原酶"},
    {"id": "cyanocobalamin", "name": "维生素B12", "category": "维生素", "generic_name": "氰钴胺",
     "contraindications": ["Leber视神经萎缩"],
     "side_effects": ["过敏反应(注射)"], "metabolism": "肝脏储存"},

    # ==================== 其他 ====================
    {"id": "tizanidine", "name": "替扎尼定", "category": "肌肉松弛剂",
     "generic_name": "盐酸替扎尼定",
     "contraindications": ["严重肝功能不全", "CYP1A2强抑制剂合用"],
     "side_effects": ["嗜睡", "低血压", "肝毒性"], "metabolism": "CYP1A2"},
    {"id": "baclofen", "name": "巴氯芬", "category": "肌肉松弛剂", "generic_name": "巴氯芬",
     "contraindications": ["癫痫"],
     "side_effects": ["嗜睡", "肌无力", "戒断综合征"], "metabolism": "部分肝脏代谢"},
    {"id": "thalidomide", "name": "沙利度胺", "category": "免疫调节剂", "generic_name": "沙利度胺",
     "contraindications": ["孕妇(强致畸)"],
     "side_effects": ["致畸", "深静脉血栓", "嗜睡"], "metabolism": "非CYP水解"},
    {"id": "danazol", "name": "达那唑", "category": "雄激素", "generic_name": "达那唑",
     "contraindications": ["孕妇", "卟啉症"],
     "side_effects": ["男性化", "肝毒性"], "metabolism": "CYP3A4"},
    {"id": "colchicine", "name": "秋水仙碱", "category": "抗痛风药", "generic_name": "秋水仙碱",
     "contraindications": ["严重肾功能不全", "严重肝功能不全"],
     "side_effects": ["腹泻", "骨髓抑制", "肌病"], "metabolism": "CYP3A4"},
]

# ========== 新增交互 ==========
EXTRA_INTERACTIONS = [
    # 心血管
    ("warfarin", "amiodarone", "critical", "胺碘酮强效抑制CYP2C9/CYP3A4,华法林血药浓度显著升高"),
    ("warfarin", "fluconazole", "critical", "氟康唑抑制CYP2C9,华法林代谢受阻,出血风险极高"),
    ("warfarin", "metronidazole", "high", "甲硝唑抑制CYP2C9,增强华法林抗凝效果"),
    ("warfarin", "cotrimoxazole", "high", "复方新诺明抑制CYP2C9,增强华法林抗凝效果"),
    ("warfarin", "fluoxetine", "high", "氟西汀抑制CYP2C9,增强华法林抗凝效果"),
    ("aspirin", "clopidogrel", "high", "双重抗血小板,出血风险显著增加"),
    ("aspirin", "ticagrelor", "high", "双重抗血小板,出血风险显著增加"),
    ("aspirin", "heparin", "critical", "抗凝+抗血小板,出血风险极高"),
    ("clopidogrel", "omeprazole", "medium", "奥美拉唑抑制CYP2C19,氯吡格雷活化受阻"),
    ("clopidogrel", "esomeprazole", "medium", "埃索美拉唑抑制CYP2C19,氯吡格雷活化受阻"),
    ("metoprolol", "verapamil", "critical", "CYP2D6抑制+双重心脏传导抑制"),
    ("metoprolol", "diltiazem", "high", "CYP2D6抑制+双重心脏传导抑制"),
    ("atenolol", "verapamil", "critical", "双重心脏传导抑制,严重心动过缓"),
    ("atenolol", "diltiazem", "high", "双重心脏传导抑制"),
    ("carvedilol", "verapamil", "critical", "双重心脏传导抑制+α阻滞,严重低血压"),
    ("bisoprolol", "diltiazem", "high", "双重心脏传导抑制"),
    ("nebivolol", "verapamil", "high", "双重心脏传导抑制"),
    ("amlodipine", "simvastatin", "medium", "氨氯地平抑制CYP3A4,他汀血药浓度升高"),
    ("verapamil", "simvastatin", "critical", "维拉帕米强效抑制CYP3A4,横纹肌溶解风险"),
    ("verapamil", "atorvastatin", "high", "维拉帕米抑制CYP3A4,他汀暴露量增加"),
    ("verapamil", "lovastatin", "critical", "维拉帕米强效抑制CYP3A4,横纹肌溶解风险"),
    ("diltiazem", "simvastatin", "high", "地尔硫卓抑制CYP3A4,他汀暴露量增加"),
    ("diltiazem", "carbamazepine", "high", "地尔硫卓抑制CYP3A4,卡马西平血药浓度升高"),
    ("verapamil", "carbamazepine", "high", "维拉帕米抑制CYP3A4,卡马西平血药浓度升高"),
    ("spironolactone", "lisinopril", "high", "双重保钾,高钾血症风险极高"),
    ("spironolactone", "losartan", "high", "双重保钾,高钾血症风险极高"),
    ("spironolactone", "potassium_chloride", "critical", "保钾利尿+补钾,高钾血症风险极高"),
    ("sacubitril_valsartan", "lisinopril", "critical", "ARNI禁忌与ACEI合用,血管性水肿风险"),
    ("digoxin", "amiodarone", "critical", "胺碘酮抑制P-gp,地高辛血药浓度升高50-100%"),
    ("digoxin", "verapamil", "high", "维拉帕米抑制P-gp,地高辛血药浓度升高"),
    ("digoxin", "clarithromycin", "critical", "克拉霉素抑制P-gp,地高辛中毒风险"),
    ("amiodarone", "flecainide", "critical", "胺碘酮+IC类,严重致心律失常风险"),
    ("amiodarone", "sotalol", "critical", "双重QT延长,尖端扭转型室速风险极高"),
    ("amiodarone", "dronedarone", "critical", "药理学重复+QT延长,禁忌合用"),
    ("amiodarone", "simvastatin", "high", "胺碘酮抑制CYP3A4,他汀暴露量增加"),
    ("flecainide", "propranolol", "high", "双重心脏传导抑制"),
    ("sotalol", "verapamil", "critical", "双重QT延长+心脏传导抑制"),
    ("dronedarone", "simvastatin", "high", "决奈达隆抑制CYP3A4/P-gp"),
    ("dronedarone", "dabigatran", "high", "决奈达隆抑制P-gp,达比加群血药浓度升高"),

    # 抗生素
    ("ciprofloxacin", "theophylline", "critical", "环丙沙星强效抑制CYP1A2,茶碱中毒"),
    ("ciprofloxacin", "tizanidine", "critical", "环丙沙星强效抑制CYP1A2,替扎尼定暴露量大幅增加"),
    ("ciprofloxacin", "warfarin", "high", "环丙沙星增强华法林抗凝效果"),
    ("ciprofloxacin", "clozapine", "critical", "环丙沙星抑制CYP1A2,氯氮平血药浓度升高"),
    ("moxifloxacin", "amiodarone", "critical", "双重QT延长"),
    ("moxifloxacin", "sotalol", "critical", "双重QT延长"),
    ("moxifloxacin", "haloperidol", "high", "双重QT延长"),
    ("levofloxacin", "warfarin", "medium", "左氧氟沙星增强华法林抗凝效果"),
    ("clarithromycin", "simvastatin", "critical", "克拉霉素强效抑制CYP3A4,横纹肌溶解"),
    ("clarithromycin", "atorvastatin", "high", "克拉霉素抑制CYP3A4,他汀暴露量增加"),
    ("clarithromycin", "carbamazepine", "high", "克拉霉素抑制CYP3A4,卡马西平血药浓度升高"),
    ("clarithromycin", "colchicine", "critical", "克拉霉素抑制P-gp/CYP3A4,秋水仙碱中毒"),
    ("clarithromycin", "verapamil", "high", "心动过缓和低血压风险"),
    ("erythromycin", "simvastatin", "critical", "红霉素抑制CYP3A4,横纹肌溶解风险"),
    ("erythromycin", "carbamazepine", "high", "红霉素抑制CYP3A4,卡马西平中毒"),
    ("azithromycin", "amiodarone", "high", "QT延长风险"),
    ("metronidazole", "alcohol", "high", "双硫仑样反应"),
    ("metronidazole", "lithium", "high", "可能升高锂盐血药浓度"),
    ("metronidazole", "fluorouracil", "critical", "甲硝唑抑制DPD,5-FU毒性增加"),
    ("cotrimoxazole", "methotrexate", "high", "抑制肾小管分泌,甲氨蝶呤蓄积"),
    ("cotrimoxazole", "warfarin", "high", "抑制CYP2C9,增强华法林抗凝效果"),
    ("cotrimoxazole", "lithium", "high", "影响肾脏排泄,锂盐血药浓度升高"),
    ("cotrimoxazole", "spironolactone", "high", "高钾血症风险叠加"),
    ("gentamicin", "vancomycin", "high", "双重肾毒性"),
    ("gentamicin", "furosemide", "high", "袢利尿剂增加氨基糖苷类肾毒性和耳毒性"),
    ("gentamicin", "amphotericin_b", "high", "双重肾毒性"),
    ("vancomycin", "amphotericin_b", "high", "双重肾毒性"),
    ("meropenem", "valproic_acid", "critical", "碳青霉烯类显著降低丙戊酸血药浓度,癫痫发作风险"),
    ("linezolid", "sertraline", "critical", "MAO抑制+SSRI,5-HT综合征风险极高"),
    ("linezolid", "fluoxetine", "critical", "MAO抑制+SSRI,5-HT综合征风险极高"),
    ("linezolid", "venlafaxine", "critical", "MAO抑制+SNRI,5-HT综合征风险"),
    ("linezolid", "tramadol", "high", "MAO抑制+阿片,5-HT综合征/癫痫风险"),
    ("linezolid", "methylphenidate", "high", "MAO抑制+兴奋剂,高血压危象风险"),
    ("nitrofurantoin", "magnesium_antacid", "medium", "抗酸剂降低呋喃妥因吸收"),
    ("rifampicin", "warfarin", "critical", "利福平强效CYP诱导,华法林效果大幅降低"),
    ("rifampicin", "oral_contraceptives", "critical", "利福平诱导CYP3A4,口服避孕药失效"),
    ("rifampicin", "simvastatin", "high", "利福平诱导CYP3A4,他汀效果降低"),
    ("rifampicin", "tacrolimus", "critical", "利福平诱导CYP3A4,他克莫司血药浓度大幅降低"),
    ("rifampicin", "cyclosporine", "critical", "利福平诱导CYP3A4,环孢素血药浓度大幅降低"),

    # 抗真菌
    ("fluconazole", "phenytoin", "high", "氟康唑抑制CYP2C9,苯妥英血药浓度升高"),
    ("fluconazole", "cyclosporine", "high", "氟康唑抑制CYP3A4,环孢素血药浓度升高"),
    ("fluconazole", "tacrolimus", "high", "氟康唑抑制CYP3A4,他克莫司血药浓度升高"),
    ("itraconazole", "simvastatin", "critical", "伊曲康唑强效抑制CYP3A4,横纹肌溶解"),
    ("itraconazole", "atorvastatin", "high", "伊曲康唑抑制CYP3A4,他汀暴露量增加"),
    ("itraconazole", "midazolam", "critical", "伊曲康唑抑制CYP3A4,咪达唑仑暴露量大幅增加"),
    ("itraconazole", "digoxin", "high", "伊曲康唑抑制P-gp,地高辛血药浓度升高"),
    ("voriconazole", "rifampicin", "critical", "利福平强效诱导CYP,伏立康唑血药浓度大幅降低"),
    ("voriconazole", "carbamazepine", "high", "卡马西平诱导CYP,伏立康唑效果降低"),
    ("voriconazole", "sirolimus", "critical", "伏立康唑抑制CYP3A4,西罗莫司暴露量大幅增加"),
    ("posaconazole", "simvastatin", "critical", "泊沙康唑强效抑制CYP3A4,横纹肌溶解"),
    ("posaconazole", "tacrolimus", "high", "泊沙康唑抑制CYP3A4,他克莫司血药浓度升高"),
    ("amphotericin_b", "furosemide", "high", "袢利尿剂加重两性霉素B肾毒性"),
    ("griseofulvin", "warfarin", "medium", "灰黄霉素诱导CYP,华法林效果降低"),
    ("griseofulvin", "oral_contraceptives", "medium", "灰黄霉素可能降低口服避孕药效果"),

    # 精神科
    ("fluoxetine", "tramadol", "critical", "SSRI+阿片,5-HT综合征+癫痫风险"),
    ("fluoxetine", "dextromethorphan", "high", "SSRI+右美沙芬,5-HT综合征风险"),
    ("fluoxetine", "lithium", "high", "SSRI增强锂盐神经毒性"),
    ("sertraline", "tramadol", "critical", "SSRI+阿片,5-HT综合征风险"),
    ("sertraline", "pimozide", "critical", "CYP2D6抑制+pimozide,QT延长风险"),
    ("paroxetine", "tamoxifen", "critical", "帕罗西汀强效抑制CYP2D6,他莫昔芬活化受阻"),
    ("fluoxetine", "tamoxifen", "critical", "氟西汀强效抑制CYP2D6,他莫昔芬活化受阻"),
    ("venlafaxine", "tramadol", "critical", "SNRI+阿片,5-HT综合征风险极高"),
    ("duloxetine", "tramadol", "critical", "SNRI+阿片,5-HT综合征风险"),
    ("duloxetine", "fluoxetine", "high", "双重5-HT再摄取抑制,5-HT综合征风险"),
    ("mirtazapine", "tramadol", "high", "5-HT综合征风险"),
    ("mirtazapine", "linezolid", "high", "MAO抑制+5-HT能药物"),
    ("trazodone", "fluoxetine", "medium", "氟西汀抑制CYP2D6,曲唑酮血药浓度升高"),
    ("lithium", "ibuprofen", "critical", "NSAIDs降低肾脏锂清除,锂中毒风险极高"),
    ("lithium", "losartan", "high", "ARB降低肾脏锂清除,锂中毒风险"),
    ("lithium", "lisinopril", "high", "ACEI降低肾脏锂清除,锂中毒风险"),
    ("lithium", "furosemide", "high", "袢利尿剂改变锂排泄"),
    ("lithium", "carbamazepine", "high", "双重神经毒性叠加"),
    ("lithium", "haloperidol", "high", "双重神经毒性,脑病风险"),
    ("valproic_acid", "carbamazepine", "medium", "丙戊酸升高卡马西平环氧化物水平"),
    ("valproic_acid", "lamotrigine", "critical", "丙戊酸抑制拉莫三嗪代谢,SJS/TEN风险极高"),
    ("carbamazepine", "erythromycin", "high", "红霉素抑制CYP3A4,卡马西平中毒"),
    ("carbamazepine", "clarithromycin", "high", "克拉霉素抑制CYP3A4,卡马西平中毒"),
    ("carbamazepine", "fluconazole", "high", "氟康唑抑制CYP3A4,卡马西平血药浓度升高"),
    ("carbamazepine", "oral_contraceptives", "critical", "卡马西平诱导CYP3A4,口服避孕药失效"),
    ("carbamazepine", "cyclosporine", "critical", "卡马西平诱导CYP3A4,环孢素血药浓度大幅降低"),
    ("carbamazepine", "tacrolimus", "critical", "卡马西平诱导CYP3A4,他克莫司血药浓度大幅降低"),
    ("lamotrigine", "valproic_acid", "critical", "丙戊酸抑制拉莫三嗪葡萄糖醛酸化,SJS/TEN风险极高"),
    ("phenytoin", "fluconazole", "high", "氟康唑抑制CYP2C9,苯妥英中毒"),
    ("phenytoin", "amiodarone", "high", "胺碘酮抑制CYP2C9,苯妥英中毒"),
    ("phenytoin", "warfarin", "medium", "苯妥英诱导CYP,华法林效果可能变化"),
    ("olanzapine", "fluvoxamine", "high", "氟伏沙明强效抑制CYP1A2,奥氮平暴露量大幅增加"),
    ("clozapine", "fluvoxamine", "critical", "氟伏沙明强效抑制CYP1A2,氯氮平血药浓度大幅升高"),
    ("clozapine", "fluoxetine", "high", "氟西汀抑制CYP2D6,氯氮平血药浓度升高"),
    ("clozapine", "carbamazepine", "critical", "卡马西平诱导CYP+骨髓抑制叠加"),
    ("clozapine", "ciprofloxacin", "critical", "环丙沙星抑制CYP1A2,氯氮平血药浓度大幅升高"),
    ("methylphenidate", "clonidine", "high", "高血压风险"),
    ("atomoxetine", "fluoxetine", "medium", "氟西汀抑制CYP2D6,托莫西汀血药浓度升高"),

    # 内分泌
    ("metformin", "contrast_dye", "critical", "碘造影剂致肾功能损害,二甲双胍蓄积→乳酸酸中毒"),
    ("metformin", "alcohol", "high", "酒精增加乳酸酸中毒风险"),
    ("glimepiride", "fluconazole", "high", "氟康唑抑制CYP2C9,磺脲类低血糖风险增加"),
    ("glibenclamide", "fluconazole", "high", "氟康唑抑制CYP2C9,磺脲类低血糖风险增加"),
    ("repaglinide", "gemfibrozil", "critical", "吉非贝齐抑制CYP2C8,瑞格列奈暴露量大幅增加"),
    ("repaglinide", "clarithromycin", "high", "克拉霉素抑制CYP3A4,瑞格列奈血药浓度升高"),
    ("levothyroxine", "calcium_carbonate", "medium", "钙剂降低左甲状腺素吸收(需间隔4小时)"),
    ("levothyroxine", "ferrous_sulfate", "medium", "铁剂降低左甲状腺素吸收(需间隔4小时)"),
    ("levothyroxine", "omeprazole", "medium", "PPI影响胃酸,可能降低左甲状腺素吸收"),
    ("levothyroxine", "amiodarone", "medium", "胺碘酮含碘,影响甲状腺功能"),
    ("insulin_glargine", "pioglitazone", "medium", "噻唑烷二酮+胰岛素,液体潴留/心衰风险增加"),

    # 呼吸
    ("theophylline", "ciprofloxacin", "critical", "环丙沙星强效抑制CYP1A2,茶碱中毒"),
    ("theophylline", "clarithromycin", "high", "克拉霉素抑制CYP3A4,茶碱血药浓度升高"),
    ("theophylline", "fluvoxamine", "critical", "氟伏沙明强效抑制CYP1A2,茶碱中毒"),
    ("theophylline", "cimetidine", "high", "西咪替丁抑制CYP1A2,茶碱血药浓度升高"),
    ("salbutamol", "propranolol", "high", "β受体阻滞剂拮抗支气管扩张效果"),
    ("budesonide", "ketoconazole", "high", "酮康唑抑制CYP3A4,吸入性激素全身暴露量增加"),
    ("fluticasone", "ritonavir", "critical", "利托那韦强效抑制CYP3A4,氟替卡松全身暴露量大幅增加"),
    ("dextromethorphan", "fluoxetine", "high", "SSRI+右美沙芬,5-HT综合征风险"),
    ("dextromethorphan", "sertraline", "high", "SSRI+右美沙芬,5-HT综合征风险"),
    ("codeine", "fluoxetine", "high", "氟西汀抑制CYP2D6,可待因无法转化为吗啡"),
    ("codeine", "paroxetine", "high", "帕罗西汀抑制CYP2D6,可待因无法转化为吗啡"),

    # 消化
    ("omeprazole", "clopidogrel", "medium", "奥美拉唑抑制CYP2C19,氯吡格雷活化受阻"),
    ("omeprazole", "diazepam", "medium", "奥美拉唑抑制CYP2C19,地西泮代谢减慢"),
    ("omeprazole", "phenytoin", "medium", "奥美拉唑抑制CYP2C19,苯妥英血药浓度可能升高"),
    ("cimetidine", "warfarin", "high", "西咪替丁抑制CYP多酶,华法林代谢减慢"),
    ("cimetidine", "theophylline", "high", "西咪替丁抑制CYP1A2,茶碱血药浓度升高"),
    ("cimetidine", "phenytoin", "high", "西咪替丁抑制CYP,苯妥英血药浓度升高"),
    ("cimetidine", "carbamazepine", "medium", "西咪替丁抑制CYP,卡马西平血药浓度升高"),
    ("cimetidine", "lidocaine_iv", "high", "西咪替丁降低肝脏血流+抑制CYP,利多卡因蓄积"),
    ("sucralfate", "ciprofloxacin", "high", "硫糖铝螯合喹诺酮类,吸收大幅降低"),
    ("sucralfate", "levothyroxine", "medium", "硫糖铝降低左甲状腺素吸收"),

    # 免疫抑制剂
    ("tacrolimus", "cyclosporine", "critical", "同类药物叠加,严重肾毒性,禁忌合用"),
    ("tacrolimus", "voriconazole", "high", "伏立康唑抑制CYP3A4,他克莫司血药浓度升高"),
    ("tacrolimus", "posaconazole", "high", "泊沙康唑抑制CYP3A4,他克莫司血药浓度升高"),
    ("tacrolimus", "erythromycin", "high", "红霉素抑制CYP3A4,他克莫司血药浓度升高"),
    ("tacrolimus", "clarithromycin", "high", "克拉霉素抑制CYP3A4,他克莫司血药浓度升高"),
    ("tacrolimus", "rifampicin", "critical", "利福平诱导CYP3A4,他克莫司血药浓度大幅降低"),
    ("tacrolimus", "carbamazepine", "critical", "卡马西平诱导CYP3A4,他克莫司血药浓度大幅降低"),
    ("cyclosporine", "voriconazole", "high", "伏立康唑抑制CYP3A4,环孢素血药浓度升高"),
    ("cyclosporine", "simvastatin", "critical", "环孢素抑制OATP/CYP3A4,横纹肌溶解"),
    ("cyclosporine", "atorvastatin", "high", "环孢素抑制OATP/CYP3A4"),
    ("cyclosporine", "rosuvastatin", "high", "环孢素抑制OATP1B1"),
    ("cyclosporine", "methotrexate", "high", "环孢素降低甲氨蝶呤肾脏清除"),
    ("cyclosporine", "NSAIDs", "high", "NSAIDs加重环孢素肾毒性"),
    ("cyclosporine", "amphotericin_b", "high", "双重肾毒性"),
    ("cyclosporine", "carbamazepine", "critical", "卡马西平诱导CYP3A4,环孢素血药浓度大幅降低"),
    ("azathioprine", "allopurinol", "critical", "别嘌醇抑制XO,硫唑嘌呤代谢物蓄积,严重骨髓抑制"),
    ("mycophenolate", "antacids", "medium", "含铝/镁抗酸剂降低霉酚酸吸收"),
    ("mycophenolate", "cholestyramine", "high", "考来烯胺降低霉酚酸肠肝循环"),
    ("leflunomide", "methotrexate", "high", "双重免疫抑制+肝毒性叠加"),

    # 抗肿瘤
    ("methotrexate_onco", "NSAIDs", "critical", "NSAIDs降低甲氨蝶呤肾脏清除,严重骨髓抑制"),
    ("methotrexate_onco", "penicillins", "high", "青霉素类降低甲氨蝶呤肾脏清除"),
    ("methotrexate_onco", "cotrimoxazole", "high", "双重抗叶酸,严重骨髓抑制"),
    ("fluorouracil", "metronidazole", "critical", "甲硝唑抑制DPD,5-FU毒性大幅增加"),
    ("fluorouracil", "warfarin", "high", "5-FU增强华法林抗凝效果"),
    ("irinotecan", "ketoconazole", "high", "酮康唑抑制CYP3A4,SN-38暴露量增加"),
    ("cisplatin", "gentamicin", "high", "双重肾毒性和耳毒性"),
    ("tamoxifen", "fluoxetine", "critical", "氟西汀抑制CYP2D6,他莫昔芬活化受阻"),
    ("tamoxifen", "paroxetine", "critical", "帕罗西汀抑制CYP2D6,他莫昔芬活化受阻"),
    ("tamoxifen", "bupropion", "high", "安非他酮抑制CYP2D6,他莫昔芬活化受阻"),
    ("capecitabine", "warfarin", "high", "卡培他滨增强华法林抗凝效果"),

    # 泌尿
    ("sildenafil", "nitroglycerin", "critical", "PDE5抑制剂+硝酸酯类,严重低血压,禁忌合用"),
    ("sildenafil", "isosorbide_dinitrate", "critical", "PDE5抑制剂+硝酸酯类,严重低血压,禁忌合用"),
    ("tadalafil", "nitroglycerin", "critical", "PDE5抑制剂+硝酸酯类,严重低血压,禁忌合用"),
    ("sildenafil", "ketoconazole", "high", "酮康唑抑制CYP3A4,西地那非暴露量大幅增加"),
    ("sildenafil", "ritonavir", "critical", "利托那韦强效抑制CYP3A4,西地那非暴露量大幅增加"),

    # 其他
    ("allopurinol", "azathioprine", "critical", "别嘌醇抑制XO,硫唑嘌呤代谢物蓄积,严重骨髓抑制"),
    ("allopurinol", "mercaptopurine", "critical", "别嘌醇抑制XO,6-MP蓄积,严重骨髓抑制"),
    ("colchicine", "clarithromycin", "critical", "克拉霉素抑制CYP3A4/P-gp,秋水仙碱中毒"),
    ("colchicine", "cyclosporine", "high", "环孢素抑制P-gp,秋水仙碱中毒风险"),
    ("febuxostat", "azathioprine", "critical", "非布司他抑制XO,硫唑嘌呤代谢物蓄积"),
    ("tizanidine", "ciprofloxacin", "critical", "环丙沙星强效抑制CYP1A2,替扎尼定暴露量大幅增加"),
    ("tizanidine", "fluvoxamine", "critical", "氟伏沙明强效抑制CYP1A2,替扎尼定暴露量大幅增加"),
    ("baclofen", "diazepam", "high", "双重中枢抑制,呼吸抑制风险"),
    ("propofol", "fentanyl", "high", "双重呼吸抑制和低血压"),
    ("epinephrine", "propranolol", "critical", "非选择性β阻滞剂+肾上腺素,严重高血压危象"),
    ("diazepam", "opioids", "critical", "苯二氮卓+阿片,呼吸抑制风险极高(黑框警告)"),
    ("diazepam", "omeprazole", "medium", "奥美拉唑抑制CYP2C19,地西泮代谢减慢"),
    ("diazepam", "cimetidine", "medium", "西咪替丁抑制CYP,地西泮代谢减慢"),
    ("lidocaine_local", "cimetidine", "high", "西咪替丁降低肝脏血流+抑制CYP,利多卡因蓄积"),
    ("bupivacaine", "propranolol", "medium", "β阻滞剂降低布比卡因肝脏清除"),
    ("danazol", "carbamazepine", "high", "达那唑抑制CYP3A4,卡马西平血药浓度升高"),
    ("cyclophosphamide", "allopurinol", "medium", "别嘌醇可能加重环磷酰胺骨髓抑制"),
    ("doxorubicin", "trastuzumab", "critical", "心脏毒性叠加(心衰风险极高)"),
    ("amiodarone", "levothyroxine", "medium", "胺碘酮含碘,影响甲状腺功能"),
]

# ========== 新增替代药物 ==========
EXTRA_ALTERNATIVES = [
    ("warfarin", "rivaroxaban", "新型口服抗凝药,无需频繁监测INR"),
    ("warfarin", "apixaban", "新型口服抗凝药,出血风险相对较低"),
    ("aspirin", "clopidogrel", "P2Y12抑制剂,单药抗血小板"),
    ("omeprazole", "pantoprazole", "泮托拉唑CYP2C19依赖较低,药物相互作用较少"),
    ("omeprazole", "rabeprazole", "雷贝拉唑非酶代谢为主,相互作用少"),
    ("cimetidine", "famotidine", "法莫替丁不抑制CYP,药物相互作用少"),
    ("glibenclamide", "gliclazide", "格列齐特低血糖风险较低"),
    ("glibenclamide", "metformin", "双胍类不引起低血糖"),
    ("diazepam", "lorazepam", "劳拉西泮不经过CYP450代谢"),
    ("diazepam", "oxazepam", "奥沙西泮仅经葡萄糖醛酸化,相互作用最少"),
    ("morphine", "acetaminophen", "轻中度疼痛可优先使用非阿片类镇痛"),
    ("morphine", "tramadol", "弱阿片类,呼吸抑制风险较低"),
    ("fluoxetine", "sertraline", "同为SSRI但CYP2D6抑制较弱"),
    ("simvastatin", "pravastatin", "普伐他汀不经CYP450代谢,相互作用最少"),
    ("simvastatin", "rosuvastatin", "瑞舒伐他汀CYP2C9少量代谢,相互作用较少"),
    ("ciprofloxacin", "azithromycin", "大环内酯类不经过CYP1A2代谢"),
    ("ciprofloxacin", "amoxicillin", "青霉素类无CYP相互作用"),
    ("carbamazepine", "levetiracetam", "左乙拉西坦不经CYP代谢,药物相互作用最少"),
    ("valproic_acid", "levetiracetam", "不经CYP代谢,相互作用少"),
    ("cyclosporine", "tacrolimus", "他克莫司肾毒性相对较轻"),
    ("cyclosporine", "sirolimus", "mTOR抑制剂,肾毒性低"),
    ("methotrexate", "mycophenolate", "吗替麦考酚酯肝毒性较低"),
    ("metformin", "empagliflozin", "SGLT2抑制剂有心血管保护作用"),
    ("metformin", "sitagliptin", "DPP-4抑制剂低血糖风险极低"),
    ("amlodipine", "lercanidipine", "乐卡地平水肿发生率较低"),
    ("losartan", "amlodipine", "钙通道阻滞剂不升高血钾"),
    ("lisinopril", "amlodipine", "钙通道阻滞剂不升高血钾"),
    ("amiodarone", "dronedarone", "决奈达隆肺/甲状腺毒性较低"),
    ("gentamicin", "amikacin", "阿米卡星耐药率较低"),
    ("doxorubicin", "epirubicin", "表柔比星心脏毒性较低"),
    ("cisplatin", "carboplatin", "卡铂肾毒性和耳毒性较低"),
    ("paclitaxel", "docetaxel", "多西他赛给药频率较低"),
]

# ========== 去重并写入文件 ==========
# 先导入现有数据获取已有 ID
import importlib
import app.graph.drug_data as dd
importlib.reload(dd)

existing_ids = {d["id"] for d in dd.DRUGS}
existing_interactions = set()
for a, b, sev, mech in dd.INTERACTIONS:
    existing_interactions.add((a, b))
    existing_interactions.add((b, a))
existing_alternatives = set()
for a, b, reason in dd.ALTERNATIVES:
    existing_alternatives.add((a, b))
    existing_alternatives.add((b, a))

# 过滤掉已存在的
new_drugs = [d for d in EXTRA_DRUGS if d["id"] not in existing_ids]
new_interactions = [(a, b, s, m) for a, b, s, m in EXTRA_INTERACTIONS
                    if (a, b) not in existing_interactions]
new_alternatives = [(a, b, r) for a, b, r in EXTRA_ALTERNATIVES
                    if (a, b) not in existing_alternatives]

print(f"新增药物: {len(new_drugs)} (去重后)")
print(f"新增交互: {len(new_interactions)} (去重后)")
print(f"新增替代: {len(new_alternatives)} (去重后)")

# 构建插入代码
import_lines = f"""
# ==================== 扩展药物数据 ====================
_EXTRA_DRUGS = {repr(new_drugs)}
DRUGS.extend(_EXTRA_DRUGS)

_EXTRA_INTERACTIONS = {repr(new_interactions)}
INTERACTIONS.extend(_EXTRA_INTERACTIONS)

_EXTRA_ALTERNATIVES = {repr(new_alternatives)}
ALTERNATIVES.extend(_EXTRA_ALTERNATIVES)

"""

marker = "\ndef build_graph_from_data():"
content = content.replace(marker, import_lines + marker)

with open("app/graph/drug_data.py", "w", encoding="utf-8") as f:
    f.write(content)

# 验证
importlib.reload(dd)
print(f"扩展完成!")
print(f"  药物: {len(dd.DRUGS)}")
print(f"  交互: {len(dd.INTERACTIONS)}")
print(f"  替代: {len(dd.ALTERNATIVES)}")
